### PR TITLE
Documentation change: "any" to "all" permissions

### PR DESCRIPTION
**Pull request by tjubutsi**
has_permissions doesn't check if any of the permission:bool combinations is satisfied, it checks all of them.

Edit: :)

### CODE REVIEW

**Comment by SilicalNZ** [comment]
Where is the evidence for said inconsistancy. A smiley face has no justifications.

**Comment by CapnS** [comment]
I mean, he's right isn't he? That check requires you to have all of the permissions, not any.

**Comment by laggycomputer** [comment]
Notice that in the code for `has_permissions`, it is possible to *disallow* permissions as well as require them. If anything, the docs should remain the same or mention that disallowing perms is possible.

**Comment by CapnS** [comment]
But why would they stay the same, all of the permissions (whether True or False) need to be correct for this to return True, not any of them. I do agree that there should be a note about being able to disallow certain permissions, but I definitely think it needs to be switched to all.

**Comment by Gorialis** [comment]
Issues (and particularly pull requests) should be descriptive, including a summary of the changes made and a rationale for doing so. Short, inspecific titles and little or no description make it more difficult to find and catalogue issues and pull requests later.

Please see the GitHub guidelines and [merged pull requests](https://github.com/Rapptz/discord.py/pulls?q=is%3Apr+is%3Amerged) to see how a good pull request should be created.

**Pull request closed without merging**
