### PR TITLE
Make implicit raw backslashes explicit

### PR DESCRIPTION
**Pull request by BeatButton**
In Python 3.8 implicit raw backslashes in strings will be deprecated. So, this.

### CODE REVIEW

**Comment by Hornwitser** [comment]
This was deprecated in Python 3.6.

**Comment by BeatButton** [comment]
Sorry, I misspoke. They'll be a straight-up error in 3.8.

**Comment by Hornwitser** [comment]
I'm unable to find any place saying this will be an error in 3.8.  [Issue32912](https://bugs.python.org/issue32912) has suggested changing it to a SyntaxWarning instead of a non-silent DeprecationWarning in 3.8 but there doesn't appear to be any movement on it.

**Comment by Hornwitser** [comment]
That does not say _when_ it'll become an error, only that it _will eventually_ become an error.

**Comment by BeatButton** [comment]
Ah, you're right, I had conflated this deprecation warning with a different one. But, regardless, it's been deprecated. There's no reason not to fix it.

**Comment by Rapptz** [comment]
This PR is wrong.

1. You shouldn't change `r` prefixed strings.
2. It's better to instead turn the docstrings into `r"""..."""` instead of the current `"""..."""` and changing every backslash into a double-backslash, per [PEP-257](https://www.python.org/dev/peps/pep-0257/).

**Comment by BeatButton** [comment]
Haha, oops, I forgot about the raw-strings thing. And that's a good point, too. Sorry for having the wrong idea.

**Pull request closed without merging**
