### PR TITLE
Embed Limits

### PR DESCRIPTION
**Pull request by BluePhoenixGame**
Changed the documentation to add all the embed limits from [here](https://discordapp.com/developers/docs/resources/channel#embed-limits)

### CODE REVIEW

**Comment by Rapptz** [comment]
Hi. Thanks for the PR.

I don't really like the wording used here. It doesn't really flow well with the rest of the prose. Chances are I'll just add it myself (since the commit message also doesn't really meet guidelines).

**Comment by BluePhoenixGame** [comment]
Okay, that seems to be my problem here, that I can't find the documentation flow.

**Comment by BluePhoenixGame** [comment]
Did this fix your problems with the PR

**Comment by BluePhoenixGame** [comment]
Using error EmbedError will be easier for newstarters as getting a HTTPException will not make that much sense. This will also make it easy for other automatic stuff.

**Comment by MusicOnline** [comment]
I don't think the library should be the one policing embed character limits. I mean, they may change at any time.

**Comment by BluePhoenixGame** [comment]
Ah, yes that is true. Although we have many things documented that could change any time, like we have here.

**Comment by BluePhoenixGame** [comment]
I now have documented EmbedError and how it is raised if the embed is over the limit

**Comment by BluePhoenixGame** [comment]
Closing this PR because discord updated their error log. New error includes the info i wanted to give out with this PR: `discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In embed: Embed size exceeds maximum size of 6000`

**Pull request closed without merging**
