### PR TITLE
Yes, command ext does have documentation

### PR DESCRIPTION
**Pull request by JustMaffie**

### CODE REVIEW

**Comment by JustMaffie** [comment]
bump

**Comment by Rapptz** [comment]
Documentation is still in an unpolished state.

**Comment by laggycomputer** [comment]
Fixed with commit `b89e5310881095558dc024c79764e2f7bdd9151d`. Why is this open? Close this...

**Comment by Harmon758** [comment]
As stated, this PR is now stale, per https://github.com/Rapptz/discord.py/commit/b89e5310881095558dc024c79764e2f7bdd9151d.

**Pull request closed without merging**
