### PR TITLE
Add URL to Asset

### PR DESCRIPTION
**Pull request by XuaTheGrate**
### Summary

Adds `Asset.url` to obtain the URL, as an alternative to `str(Asset)`.

### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by apple502j** [comment]
Just use `str(Asset)` ~~or `Asset._url`~~

**Comment by XuaTheGrate** [comment]
Using `Asset.__str__()` was on average `.001` seconds faster according to this, but if its too small to matter then I'll change it.
test
(I ran it a few times, got roughly the same result.)

**Comment by Rapptz** [comment]
Don't really see the point in this one.

**Comment by BluePhoenixGame** [comment]
This would improve readability in code I would say. It's easier to understand what `Asset().url` does VS `str(Asset)`, both is as easy to read for someone who knows all this. But it's easier for new people to read someones code and understand it.

**Comment by NCPlayz** [comment]
The behaviour is documented. You could say the same about [``str(User)``](https://discordpy.readthedocs.io/en/latest/api.html#discord.User), which gives back ``name#discrim``, but this behaviour is also documented so I feel like you can't *really* be confused here.

This also follows the style of [yarl.URL](https://yarl.readthedocs.io/en/latest/api.html), where ``str(URL)`` returns the full URL in string format.


On Apr 16, 2019 4:32 PM, BluePhoenixGame <notifications@github.com> wrote:

This would improve readability in code I would say. It's easier to understand what Asset().url does VS str(Asset), both is as easy to read for someone who knows all this. But it's easier for new people to read someones code and understand it.

**Comment by Rapptz** [comment]
The readability argument has no grounds in the actual reality of the library. You receive these through properties that end in `_url`. What you're proposing is practically a readability boost when you do `m.avatar_url.url` which is asinine.

**Comment by XuaTheGrate** [comment]
My main reason I requested this was because in the Assets repr, it would show `<Asset url=https://.../>`, and I don't know about anyone else but this makes me think that `url` is an attribute of Asset and I should be able to access it that way.

I do understand your point that it makes readability kinda wack and thinking back, it would end up being kinda weird.

**Pull request closed without merging**
