### PR TITLE
Add some commenting to the example code

### PR DESCRIPTION
**Pull request by IanGolsby**
Makes it a teensy bit easier for newcomers to see what exactly is going on

### CODE REVIEW

**Comment by NCPlayz** [comment]
Everything is in the docs, so I don't really understand this

**Comment by IanGolsby** [comment]
It's not like the most useful thing ever done to this readme file but it makes it easier for people who have trouble with docs (cause some people just don't like reading them) or people who are too lazy to click on the docs link. Also some people like to not have to look at the docs when they're trying to decide to get something, so this makes it easier for someone looking at the readability of discord.py

**Comment by Helehelehele** [comment]
> cause some people just don't like reading them

And why do we care about them?

**Comment by Vexs** [comment]
This all feels like 

`if a is b #checks if a is an instance of b`

**Comment by TheTrain2000** [comment]
If you don't like reading docs, I doubt you're going to like reading basic comments. I feel that these comments are extremely unnecessary, in that the code explains itself fairly well.

`people who are too lazy to click on the docs link`

Also, if you're too lazy to click on links for the documentation, then you're going to have a hard time using this library.

**Comment by Rapptz** [comment]
Thanks for the PR.

However I don't think I like these excessive comments since the code is pretty clear as is and the comments aren't really adding much. If someone is confused they can just check the documentation rather than having trivial comments littered across the example code.

**Comment by Rapptz** [comment]
Thanks for the PR.

However I don't think I like these excessive comments since the code is pretty clear as is and the comments aren't really adding much. If someone is confused they can just check the documentation rather than having trivial comments littered across the example code.

**Pull request closed without merging**
