### PR TITLE
Refactor Colour to Color

### PR DESCRIPTION
**Pull request by elainaaa**
## Summary

Since Colour is not true english, it might confuse users of its meaning so it should be changed to Color.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TheRockettek** [comment]
England made english

**Comment by Tari-dev** [comment]
There is nothing wrong with Colour and Color.
It's just a regional thing.

**Comment by Daggy1234** [comment]
> Since Colour is not true english, it might confuse users of its meaning so it should be changed to Color.

True English?

**Comment by scrazzz** [comment]
https://www.grammarly.com/blog/color-colour/

**Comment by MinisBett** [comment]
BIG plus for this, please, PLEASE merge this pr!!

**Comment by RealistikDash** [comment]
Americans butchering the language and enforcing it on everyone smh

**Pull request closed without merging**
