### PR TITLE
Add commands ext docs

### PR DESCRIPTION
**Pull request by jaydenkieran**
Oh boy. As docs don't currently exist for the commands ext module, I made them myself. Basic, little explanation, temporary solution.

Resolves part of #27

### CODE REVIEW

**Comment by ButterCheezii** [comment]
[I'm pretty sure Danny would have done this by now if he had time to do it.](http://discordpy.readthedocs.io/en/latest/faq.html#is-there-any-documentation-for-this)

**Comment by Rapptz** [comment]
We use international spelling here. Thanks for your comment though.

**Comment by ButterCheezii** [comment]
Understood.

**Comment by jaydenkieran** [comment]
@ButterCheezii There really wasn't a need to comment on a PR that is over 2 months old. Danny spoke to me the moment this PR was opened anyway, so I'm aware on his stance, cheers

**Pull request closed without merging**
