### PR TITLE
Jofthe v patch 1 pypy release.package

### PR DESCRIPTION
**Pull request by JoftheV**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by JoftheV** [comment]
Approve and run

**Review by JoftheV — COMMENTED** [review]
Approve and run

**Review by JoftheV — COMMENTED** [review]
Approve and run

**Comment by Rapptz** [comment]
Thanks for the PR, but no thank you.

**Pull request closed without merging**
