### PR TITLE
Remove Bot.self_bot

### PR DESCRIPTION
**Pull request by Tari-dev**
Remove Bot.self_bot since all methods of selfbots are being removed in 2.0

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by binex-dsk** [comment]
>all methods to selfbot is being removed in 2.0

cringe and bluepilled

**Comment by Cryptex-github** [comment]
I don't think the self_bot parameter is related to selfbot tho, the self_bot parameter means the bot will listen to commands invoked by itself rather then ignoring itself.

**Comment by Dorukyum** [comment]
> I don't think the self_bot parameter is related to selfbot tho, the self_bot parameter means the bot will listen to commands invoked by itself rather then ignoring itself.
> 
> 

As line 1055 states, if the kwarg is set to True the bot will **only** listen to itself. So it's directly related to self-bots.

**Review by Rapptz — APPROVED** [review]
This PR has some minor performance issues but thanks I'll fix them later.

**Comment by Gorialis** [comment]
It doesn't. This is about selfbots, aka userbots, and has nothing to do with cogs. Also, this change is old anyway.

**Pull request merged**
