### PR TITLE
Guild Scheduled Event Recurrence

### PR DESCRIPTION
**Pull request by DA-344**
## Summary

This PR adds support for Guild Recurrence. Just new parameters, edited types and new object class.

This PR will stay draft until I get some more parameter values and it gets documented in the Discord API Docs.

*While pulling 'master' to this PR, there were conflicts I fixed, but Git now thinks I edited 'voice_state.py' file when I didn't, so sorry if it is annoying to review changes with it. The same with Japanese index.po file. Sorry 🙇‍♂️!*

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Please do not touch .po files they're automatically generated.

**Comment by DA-344** [comment]
Yeah, I know, but I merged the 'master' branch and now it looks like I have edited it :(

**Comment by Rapptz** [comment]
The reason why it thinks it's edited is because it's got merge conflicts in it. You might be better off redoing the PR if you don't know how to rebase your commits to clean it up.

**Comment by DA-344** [comment]
Ok!

**Pull request closed without merging**
