### PR TITLE
Fix Piped Audio Input Ends Prematurely

### PR DESCRIPTION
**Pull request by thedtvn**
## Summary

check out [#9001](https://github.com/Rapptz/discord.py/issues/9001)

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by kairi003** [comment]
Hi @thedtvn ,

I found this closed PR #9188 related to #9001 and noticed that it was closed without specific comments. The proposed changes seem like a good solution to the issue.

Could you please share the reason for closing the PR? Was there any feedback from maintainers or other contributors that led to closing it? I'm also facing the same issue and would like to contribute a fix based on your previous work.

Thank you for your help!

Best,
kairi

**Comment by thedtvn** [comment]
@kairi003 ye i see that no one look at this so i close you need me to reopen this ??

**Comment by thedtvn** [comment]
> Hi @thedtvn ,
> 
> I found this closed PR #9188 related to #9001 and noticed that it was closed without specific comments. The proposed changes seem like a good solution to the issue.
> 
> Could you please share the reason for closing the PR? Was there any feedback from maintainers or other contributors that led to closing it? I'm also facing the same issue and would like to contribute a fix based on your previous work.
> 
> Thank you for your help!
> 
> Best, kairi

@kairi003 I has delete fork so it close sory

**Comment by kairi003** [comment]
I also encountered the same bug, and I thought this was a necessary and sufficient fix. It's unfortunate that you have already deleted the fork, but I understand. I will consider creating a new PR. Thank you.

**Pull request closed without merging**
