### PR TITLE
Allow some decorators to be used without calling them

### PR DESCRIPTION
**Pull request by bryanforbes**
### Summary

Currently, to use `Bot.listen()`, `Cog.listener()`, `commands.command()`, `commands.group()`, `Group.command()`, `Group.group()`, `commands.guild_only()`, `commands.is_owner()`, and `commands.is_nsfw()`, you must call them as part of the decorator:

```python
@bot.command()
@commands.guild_only()
async def foo(ctx):
    ...
```

This PR changes all of these decorators so they can be used without being called:

```python
@bot.command
@commands.guild_only
async def foo(ctx):
    ...
```

### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Gorialis** [comment]
I personally disagree with this change as I think the inconsistency will make the confusion not worth the convenience. If a decorator works such that it **can** accept arguments, making it optionally not have brackets may mislead people into not knowing or not understanding that such a thing is possible.

In this sense, I think that this actually works *against* QOL, as it merely scrapes up mistakes instead of actually teaching people how to use the library properly.

**Comment by Rapptz** [comment]
This discussion came about because the standard library already implements this behaviour in some of its decorators, mainly `@dataclass` in 3.7, which can be called `@dataclass()`, `@dataclass(...)` or `@dataclass`.

Since there is pre-existing standard for this behaviour to exist in the Python standard library itself, along with removing a common noob trap that aims to just have cognitive overhead. A lot of decorators can be called with arguments but a lot of them can't be called with arguments, e.g. `@property`, `@functools.lru_cache()` but do you have to care to memorize all of them?

Overall I feel like the pros outweighs the cons here -- which from what I'm gathering seems to be worrying over a hypothetical scenario of preventing people from learning something, when in reality it does no such thing as usage and documentation will prove that it *can* be called with arguments but it is not *required* to.

**Comment by bryanforbes** [comment]
I added back the `()` in the docs and added notes in a few places to note that the decorators can be used without `()`.

**Comment by GetRektByMe** [comment]
I approve this also

**Comment by NCPlayz** [comment]
Reopen this perhaps? Was closed as @bryanforbes did not change the merging branch from `rewrite` to `master` before `rewrite` was deleted.

**Pull request closed without merging**
