### PR TITLE
fix: library stub not found

### PR DESCRIPTION
**Pull request by SaidBySolo**
## Summary

```py
# sample.py
from discord import app_commands

app_commands.command()
```
When I check the file with mypy, it says that the stub cannot be found.

``discord\app_commands\commands.py:89: error: Cannot find implementation or library stub for module named "discord.ext.commands"``

https://github.com/Rapptz/discord.py/pull/7743#issuecomment-1074682871
Perhaps it has something to do with the issue comment.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by mikeshardmind** [comment]
I can't reproduce the issue this intends to fix.

```
(.venv) PS > Get-Content .\scratch.py

import discord
from discord import app_commands


@app_commands.command()
async def test(interaction: discord.Interaction):
    ...
(.venv) PS > mypy --namespace-packages .\scratch.py 
Success: no issues found in 1 source file
```

You might need to add namespace-packages to your mypy config

```
(.venv) PS > mypy --no-namespace-packages .\scratch.py    
.venv\lib\site-packages\discord\app_commands\commands.py:72: error: Cannot find implementation or library stub for module named "discord.ext.commands"
.venv\lib\site-packages\discord\app_commands\commands.py:72: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

which is something the error actually points you to

**Comment by SaidBySolo** [comment]
```
sample/
├─ __init__.py
├─ main.py
```

```py
# main.py
import discord
from discord import app_commands

@app_commands.command()
async def main(interaction: discord.Interaction) -> None:
    ...
```

`` mypy ./sample --strict``

This is a reproducible example.

Incidentally, as noted in the issue comments, I don't think this is an ideal import.

**Comment by mikeshardmind** [comment]
As pointed out previously, you can resolve this as a configuration change. mypy supports changing the behavior of import discovery. Trimming what I had above to only what's needed to show that, and including the error from mypy which *also* informed you of this:

```
(.venv) PS > mypy --strict --namespace-packages .\scratch.py 
Success: no issues found in 1 source file
```
vs
```
(.venv) PS > mypy --strict .\scratch.py
.venv\lib\site-packages\discord\app_commands\commands.py:72: error: Cannot find implementation or library stub for module named "discord.ext.commands"
.venv\lib\site-packages\discord\app_commands\commands.py:72: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

**Comment by SaidBySolo** [comment]
Actually, I don't know.

I mostly use strict type hints.

However, when I checked using the following command ``mypy sample``, I was able to reproduce that there was no problem.

There seems to be no problem in normal use.

Can you tell me what your opinion is? @mikeshardmind

**Comment by SaidBySolo** [comment]
@mikeshardmind 
Changing the mypy configuration in my project is a bit tricky because of one discord.py.

Are there any problems with these code changes?

**Comment by mikeshardmind** [comment]
> I don't like changing the configuration of my mypy because of one discord.py.

mypy's error there literally tells you to do this if this is the reason for it not detecting the import, see the link in the error message. Beyond this, you can change it on a per-package basis. you don't need to change the behavior globally.

> Are there any problems with these code changes?
Possibly (such as inconsistencies in import, churn for no tangible gain, etc) but I wasn't exactly reviewing the code, just pointing out that this shouldn't be an issue.

**Comment by SaidBySolo** [comment]
In my opinion, considering the issues mentioned above, I think these changes are meaningful changes to maintain consistency.

**Review by Rapptz — COMMENTED** [review]
Thanks. Though I can't make any promises that I'll care about this for internal code. My comment pertained to external code. What @mikeshardmind said is correct, considering discord.py makes extensive use of namespace packages you need to enable the feature for it to work as expected on mypy.

**Comment by richfromm** [comment]
Fwiw, I am able to reproduce this problem with discord.py 2.0.1 and mypy 0.982 and python 3.10.7, but in a bizarre way, it alternates between failing and passing:
https://github.com/bryanforbes/discord.py-stubs/issues/171#issuecomment-1270945026
https://github.com/bryanforbes/discord.py-stubs/issues/171#issuecomment-1270949957

But from inspection (ony) I'm wondering if the fix is correct or not:
https://github.com/Rapptz/discord.py/commit/e1961676a979e0684833bd90f1b7f74fe766677c#r86069248
https://github.com/Rapptz/discord.py/commit/e1961676a979e0684833bd90f1b7f74fe766677c#r86069343

**Comment by Rapptz** [comment]
Are you running mypy with `--namespace-packages`?

**Pull request merged**
