### PR TITLE
Update MissingRequiredArgument exception message

### PR DESCRIPTION
**Pull request by jacklin213**
Changed message from "is a required argument that is missing" to "has a required argument that is missing"

### CODE REVIEW

**Comment by Rapptz** [comment]
This message is incorrect.

The current message says "<name of parameter> is a required..." yours says "<name of parameter> has a required...".

**Comment by jacklin213** [comment]
Tested it earlier on a discord server when I was running a command
!test 
when the command expected 1 argument, the error message produced was
```test is a required argument that is missing```
which I believe is incorrect??

**Comment by Phxntxm** [comment]
Then you named the parameter you are requiring "test". The parameter that is missing, is what is named there.

**Comment by jacklin213** [comment]
@Phxntxm ah yes you are correct, My mistake. Went back and took a look now and my parameter was named "test" 
Sorry about that

**Pull request closed without merging**
