### PR TITLE
Use warnings instead of logging for the PyNaCl warning

### PR DESCRIPTION
**Pull request by iomintz**
## Summary

According to https://docs.python.org/3/howto/logging.html#when-to-use-logging
logging.warning() should only be used if the situation cannot be resolved.

This is a draft PR because I would like a review on the documentation changes first.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by iomintz** [comment]
I just noticed https://github.com/Rapptz/discord.py/issues/1719#issuecomment-437703581. I did not realize that this was possible, but I still believe the current code to be a misuse of `logging.warning`. I will update the metadata for this change set to reflect this.

**Comment by Rapptz** [comment]
I don't think these guidelines are strictly true. The standard library even offers a way to convert `warning` module calls into `logging` calls.

**Comment by iomintz** [comment]
I don't see that in the docs, would you mind linking to that?

**Comment by Rapptz** [comment]
https://docs.python.org/3/library/logging.html#logging.captureWarnings

**Comment by iomintz** [comment]
I don't see how this is a counterpoint to the guidelines employed in this PR, as it's a conversion in the opposite direction.

**Comment by Rapptz** [comment]
I don't really see much of a point in this PR. The warning mechanism is quite bad, most go ignored by default and while that's true from a logging perspective as well this is remedied by the fact that its usage is documented and there is a way for the library to aid the user into seeing the logs.

Anyway a better suggestion would be to just change this warning completely or remove it but that's for another patch set.

**Pull request closed without merging**
