### PR TITLE
Added __del__ method to client class.

### PR DESCRIPTION
**Pull request by mariohackandglitch**
Added ` __del__ `method to client class. This method calls self.close() to ensure the connection is properly closed if the client object is destroyed.

### CODE REVIEW

**Comment by NCPlayz** [comment]
What kind of scenario would you use this where you can't use Client.logout() or Client.close()

**Comment by NCPlayz** [comment]
image
Also, you might've missed this piece of info.

**Comment by mariohackandglitch** [comment]
This ensure the connection is closed in case the python interpreter suddenly exits. (However, looks like not always the interpreter calls all the destructors on exit tho 🤔).
I'm also not sure if you meant that I missed I can just call .close() myself, or that the function is a coroutine. If you meant the second case, then my first guess would be adding `await` to the close() method call, but I'm probably most likely wrong.

**Comment by Gorialis** [comment]
`__del__` is not an coroutine and therefore cannot await `self.close`, nor should it, really. Please test your commits before making PRs.

**Comment by mariohackandglitch** [comment]
Ok then...

**Pull request closed without merging**
