### PR TITLE
Add missing params `default_reaction_emoji` and `default_forum_layout` to `create_forum`

### PR DESCRIPTION
**Pull request by Puncher1**
## Summary

This PR adds 2 missing parameters `default_reaction_emoji` and `default_forum_layout` to `Guild.create_forum`

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by Rapptz — APPROVED** [review]
This PR (and the previous one) is misusing `MISSING` and `None` but I'll fix it myself later.

**Comment by Puncher1** [comment]
Ah yeah, sorry I missed that. So, for my understanding, is the following correct?: 

- `var: x = MISSING` means it's not required but that you can "catch" it you use `MISSING`
- `var: Optional[x] = None` means it's not required too, but if not set it's sent as a `null` value to the endpoint. 
- `var: Optional[x] = MISSING` means the same as the first except of being able to be `None`. E.g. this is used in an `edit` method.

**Comment by Rapptz** [comment]
Yes. Though using `Optional[X] = None` is also there for compatibility in some methods.

**Comment by Puncher1** [comment]
Alright! Thanks

**Pull request merged**
