### PR TITLE
fix: Remove useless overload

### PR DESCRIPTION
**Pull request by CaedenPH**
## Summary

Removes a useless overload

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Not useless. It's the base fallback case.

**Comment by CaedenPH** [comment]
@Rapptz How does that differ from the actual `parse_time` function which accepts `Optional[str]`? The overload is the same as the function types - 
What does 
```py
@overload
def parse_time(timestamp: Optional[str]) -> Optional[datetime.datetime]:
    ...

def parse_time(timestamp: Optional[str]) -> Optional[datetime.datetime]:
```
do opposed to just 
```py
def parse_time(timestamp: Optional[str]) -> Optional[datetime.datetime]:
```?

**Comment by Rapptz** [comment]
The way overloads work is that they ignore the "implementation" type hints.

**Comment by CaedenPH** [comment]
> The way overloads work is that they ignore the "implementation" type hints.

Oh, I wasn't aware

**Comment by bijij** [comment]
Mainly so the body of the implimentation itself can be type-checked during development.

**Pull request closed without merging**
