### PR TITLE
Allow webhooks to send emojis from other servers

### PR DESCRIPTION
**Pull request by Znunu**
### Summary

Currently webhooks only allow custom emojis from the server they belong to. Sending an auth header with each request to the webhook, makes the webhook behave more like normal messages coming from the bot, allowing emojis from other servers. I've only added this feature to webhooks made through `Webhook.from_state()` since those have the token readily available in their state attribute. An idea could be allowing any token to be passed to manually created webhooks.

### Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes. (N/A?)
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
This behaviour is unsupported and a bug on Discord's end: https://github.com/discord/discord-api-docs/pull/1631

**Comment by Znunu** [comment]
Indeed, but this bug hasn't been patched for a long time. This lib isn't affiliated with discord or anything, so I don't see what we stand to lose. Right now the lib is simply missing out. If the bug is patched, nothing is going to break. There's already a major bot, build around this very behavior.

**Comment by Rapptz** [comment]
That mentality doesn't really work in this library. Maintenance burden for a Discord bot is not something I want to add.

**Comment by Znunu** [comment]
Really don't see how this is a maintenance burden

**Pull request closed without merging**
