### PR TITLE
[commands] add require_var_positional

### PR DESCRIPTION
**Pull request by khazhyk**
Allow command require_var_positional=True to require[commands] add require_var_positional

Add command require_var_positional=True to require at least one
argument to var_positional argument types.
Defaults to False, as previous behavior.

### CODE REVIEW

**Comment by Rapptz** [comment]
How is this any different from `command(arg, *args)`?

**Comment by khazhyk** [comment]
with require_var_positional=False args can be []. You can do something similar by doing `arg args` and then concatenating the list yourself, but this is more true to the intentions - i want a non-empty list of args

**Comment by khazhyk** [comment]
RIP brutally closed

**Comment by Rapptz** [comment]
Remake it then

**Pull request closed without merging**
