### PR TITLE
Make setup.py executable

### PR DESCRIPTION
**Pull request by bmintz**

### CODE REVIEW

**Comment by Hornwitser** [comment]
Why do you want this change?

**Comment by bmintz** [comment]
Cause I had to run `setup.py sdist` to test something, and it's easier to run `./setup.py sdist` than to run `python3 setup.py sdist`. Also, a file which is intended to be run as a script should generally be marked as such.

**Comment by bmintz** [comment]
The argument for marking this as a script is the same as for any other script: it's an executable file. You're not meant to import it. Same goes for main.py or bot.py or launcher.py or whatever.

**Comment by c-x-berger** [comment]
No, you;re not meant to import it.  
You're meant to execute it with `python setup.py dist`.

**Comment by bmintz** [comment]
Right. Which is why a shebang is a good idea, since executing ./setup.py sdist inside  a venv would run it with the current python (and is shorter)

**Comment by bmintz** [comment]
This pull request is merely for convenience.

A possible issue is trying to execute setup.py but you meant a different python than the one on your PATH. Example: venv/bin/python setup.py would not be the same as ./setup.py if the venv is not activated. However, this is a rare use case so I don't anticipate that this drawback would outweigh the convenience benefit.

**Comment by Gorialis** [comment]
I don't mind this change. It's out of typical convention, but it's not like doing this removes or changes any existing functionality or workflow. My only argument would be that if we're going down this route, we might as well add the [encoding header](https://github.com/Rapptz/discord.py/blob/rewrite/discord/__init__.py#L1) as well:

https://github.com/Rapptz/discord.py/blob/rewrite/discord/__init__.py#L1

**Comment by bmintz** [comment]
Good fight everyone 🙇

**Pull request closed without merging**
