### PR TITLE
Removed broken argument from send_message

### PR DESCRIPTION
**Pull request by TheConfuZzledDude**
With that "*" argument in, you become unable to send tts through the bot

### CODE REVIEW

**Comment by Rapptz** [comment]
That * is meant to be there. It's a keyword only argument. Python 3+ only. I suggest you stop using python 2.7.

**Comment by TheConfuZzledDude** [comment]
I am using Python 3.4.3. I just confirmed it through sys.version_info, and it still gives me crap about "giving 4 positional arguments when 3 are required"

**Comment by Rapptz** [comment]
http://stackoverflow.com/q/1419046/1381108

**Comment by TheConfuZzledDude** [comment]
ahh ok got it. not a very well documented feature :/ sorry bout that

**Comment by Rapptz** [comment]
It is documented: http://discordpy.readthedocs.org/en/latest/migrating.html#forced-keyword-arguments

**Comment by TheConfuZzledDude** [comment]
I meant in python's own documentation. Yours is rather good

**Pull request closed without merging**
