### PR TITLE
Fix rich presence asset image resolution

### PR DESCRIPTION
**Pull request by kairusds**

### CODE REVIEW

**Comment by ir-3** [comment]
Correct me if I am wrong but, aren't the assets already the necessary sizes?

**Comment by kairusds** [comment]
@ir-3 not its not, it only returns low res images

**Comment by ir-3** [comment]
I think those are just for viewing the specific assets for both the large and small rich presence images, not for changing the size of them.

**Comment by kairusds** [comment]
@ir-3 oh okay

**Pull request closed without merging**
