### PR TITLE
Add AppCmdPermissions update event

### PR DESCRIPTION
**Pull request by z03h**
## Summary

adds new event
## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Heurican** [comment]
what does "adds an event" mean? could you be more specific?

**Comment by Rapptz** [comment]
This stomps all over the previous work of the previous PR that made `guild` non-optional by using an unavailable fallback. I suggest changing it and fixing it so it doesn't reintroduce issues brought up from the earlier PR.

**Review by Rapptz — CHANGES_REQUESTED** [review]
I don't want to shorten "command" to "cmd", even if it leads to extra long event and class names here.

**Review by Rapptz — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
