### PR TITLE
Fix BaseUser.permissions_in

### PR DESCRIPTION
**Pull request by tedle**
### Summary

User objects don't have roles, so they need to be converted to Member objects first.

Example:
```
import discord

client = discord.Client()

@client.event
async def on_ready():
    for guild in client.guilds:
        print(f"{guild.name}")
        for channel in guild.channels:
            permissions = client.user.permissions_in(channel)
            print(f"\t{channel.name}:{permissions}")
    await client.logout()

client.run("token")
```
Results in:
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/discord.py/discord/client.py", line 296, in _run_event
    await coro(*args, **kwargs)
  File "test.py", line 10, in on_ready
    permissions = client.user.permissions_in(channel)
  File "/discord.py/discord/user.py", line 223, in permissions_in
    return channel.permissions_for(self)
  File "/discord.py/discord/abc.py", line 426, in permissions_for
    roles = member.roles
AttributeError: 'ClientUser' object has no attribute 'roles'
```

### Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by BluePhoenixGame** [comment]
This doesn't make sense, a User object represents a discord user. Not a guild member, and so it shouldn't be linked to any channel. If you want the bot as a member you can use attribute `.me` of guild. Or it might be of channel.

**Comment by IngeniousCoder** [comment]
To refer to client.user in the current guild, use guild.me

**Comment by tedle** [comment]
> This doesn't make sense, a User object represents a discord user.

This is just a fix for broken code that already exists in the User class. It's not adding anything.

> To refer to client.user in the current guild, use guild.me

I thought about this but wasn't sure if all instances of User were guaranteed to be the client, since ClientUser and User are 2 separate classes and this fix applies to both of them.

**Comment by IngeniousCoder** [comment]
> all instances of User were guaranteed to be the client

No. A user object can represent any discord user.

**Comment by Rapptz** [comment]
This is working by design. It's a forwarding function. Your code is just a bandaid towards a misunderstanding on the function. If in a DM context for example the code equally breaks.

If you want to fix *your* code then you should probably use `guild.me.permissions_in(channel)`.

**Comment by tedle** [comment]
@Rapptz In that case shouldn't `permissions_in` be removed from BaseUser and defined exclusively in Member? Right now ClientUser and User are both have a documented function that cannot work in any circumstance since it tries to access a `.role` attribute that understandably does not exist.

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.GroupChannel.permissions_for

**Comment by tedle** [comment]
@Rapptz Ah, okay thank you for clearing up my misunderstanding. I didn't know the API well enough to realize that permissions existed outside of guild channels. The docs for the ClientUser and User implementations of `permissions_in` both claim it's an alias of `abc.GuildChannel` which only takes Members, but I guess theres no `abc.PrivateChannel` implementation to point to since `DMChannel.permissions_for` and `GroupChannel.permissions_for` have different signatures.

**Pull request closed without merging**
