### PR TITLE
Added default_setup parameter to load_extension

### PR DESCRIPTION
**Pull request by OrangutanGaming**
### Summary

Adds `default_setup` parameter to `load_extension` and the other relavent methods.

### Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by OrangutanGaming** [comment]
Could also pass if the variable starts with `__`, wasn't 100% sure if that's needed.

**Comment by Hornwitser** [comment]
What is the rationale behind this?  How would you use this?  Have you considered any alternatives to this?

**Comment by OrangutanGaming** [comment]
It's based off #2222 and I realised that since practically everyone uses the same code anyway, why even have people do it when it can be done by the library.
If you have lots of cogs in one file or just want a cleaner file, this would provide a way to have the library deal with it instead, so you would just not define a `setup` and set the `kwarg` to True.
Comparing it to some of the other ideas suggested in the discord, I think this is one of the best ways this idea could be implemented.

**Comment by Hornwitser** [comment]
I still do not understand how you're supposed to use this.

**Comment by OrangutanGaming** [comment]
You use `bot.load_extension('cog', default_setup=True)`, and if the extension does not have a `setup` defined, it will make one for you

**Comment by Hornwitser** [comment]
You didn't actually test this did you?  Your setup function looks for an instance of `Cog` (or any subclasses of it), not a class itself, and then treats it like it was a cog class.

**Comment by Hornwitser** [comment]
My main objection to this is that it's unnecessary troublesome magic.  What you save is approximately 2 lines of code per extension.  But what you get is poorly behaving magic, where the right behavior is difficult to even imagine.  Consider a cog implementation that uses a base class, will the base class be included?  What if you have an extension with multiple cogs imported from separate files?  What if you don't find any cogs, do you ignore that or error out?

**Comment by Rapptz** [comment]
This type of functionality is not one I ever want to propagate.

The idea that a cog is equivalent of a lazy extension is one that I go out of my way to dispel not one that I want to propagate. For this reason any PR offering shortcuts that blur the line between them even more is not one I want to accept.

**Pull request closed without merging**
