### PR TITLE
Add Number type (10) to Application Command Option types.

### PR DESCRIPTION
**Pull request by bijij**
## Summary

Adds Number type to application command option data types.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by SNvMK** [comment]
is it already on docs?

**Comment by joseywoermann** [comment]
> is it already on docs? and does it work?

It's in the Canary API and there is an open [PR](https://github.com/discord/discord-api-docs/pull/3455) for the documentation.

**Comment by Rapptz** [comment]
This API is in limbo according to the devs so it's gonna need to wait until it's stable.

**Comment by bijij** [comment]
Seems like the documentation was merged into the API doc's today so possibly stable now.

**Pull request merged**
