### PR TITLE
Updated Decorator's code.

### PR DESCRIPTION
**Pull request by Diakarus**
Error on my half, Decorator had the proper code but I didn't input it properly. Decorator also has been blocked by Danny, So I am posting it on Decorator's behalf.

### CODE REVIEW

**Comment by khazhyk** [comment]
what is the point of this change

**Comment by Diakarus** [comment]
Dunno, Decorator said my spacing was wrong so I fixed it. Didn't know if it was pointless or not, either way Decorator can't pull on their own because they're blocked apparently.

**Comment by Diakarus** [comment]
"also tell him this change instead of writing thread exceptions to console it will write them in discord.py's logging module to" - Decorator

**Comment by khazhyk** [comment]
decorater is blocked for a reason, i think

**Pull request closed without merging**
