### PR TITLE
Stop asyncio.async throwing a syntax error in 3.7.

### PR DESCRIPTION
**Pull request by bmintz**
Maintains support for < 3.4.4

### CODE REVIEW

**Comment by gtmanfred** [comment]
@Rapptz can a new version be released with this in it?

**Comment by Hornwitser** [comment]
This will not happen.  The async branch has been abandoned and will not see any further updates.  Use the rewrite branch if you need support for 3.7.

**Comment by gtmanfred** [comment]
Is there a released version of the rewrite branch?

**Comment by Harmon758** [comment]
Not on PyPI, no. You can install it directly from the repository.

**Pull request merged**
