### PR TITLE
Add coro to docstring

### PR DESCRIPTION
**Pull request by ster-phys**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by jack1142** [comment]
Here's a couple more:
```
discord/channel.py:TextChannel.follow
discord/ext/commands/help.py:DefaultHelpCommand.send_pages
discord/ext/commands/help.py:MinimalHelpCommand.send_pages
discord/app_commands/tree.py:CommandTree.set_translator
discord/ui/view.py:View.wait
```

There are also a couple of callbacks that need to be coroutine where this may be intentionally omitted but I'm not sure so here's a list of those:
```
discord/ext/commands/cog.py:Cog.cog_command_error
discord/ext/commands/cog.py:Cog.cog_app_command_error
discord/ext/commands/cog.py:Cog.cog_before_invoke
discord/ext/commands/cog.py:Cog.cog_after_invoke
```

**Comment by ster-phys** [comment]
Thanks!
I will add the above five to the next commit.

You said they may be intentionally omitted, do you know what the intention is?

**Comment by Rapptz** [comment]
It's not intentional, looks like a mistake.

**Comment by ster-phys** [comment]
I fixed all of the above.

**Review by Rapptz — APPROVED** [review]
Thanks!

**Pull request merged**
