### PR TITLE
Updated permissions class methods

### PR DESCRIPTION
**Pull request by TheOneMusic**
## Summary

The Discord UI has recently changed its permission categories, which are as follows:
- **General Permissions** no longer have the `administrator`, `create_instant_invite`, `change_nickname`, `manage_nicknames`, `kick_members` and `ban_members` permissions. It now has the `view_channel`/`read_messages` permission.
- New **Membership Permissions** which contain `create_instant_invite`, `change_nickname`, `manage_nicknames`, `kick_members` and `ban_members` permissions
- **Text Permissions** no longer have the `view_channel`/`read_messages` permission (this has been moved to the **General Permissions**).
- New **Advanced Permissions** which only contain the `administrator` permission.

The commit is therefore reflecting these changed. More specifically:
- [`Permissions.general()`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L162) has been updated according to the Discord UI general permissions.
- Added `Permissions.membership()` which contains the `create_instant_invite`, `change_nickname`, `manage_nicknames`, `kick_members` and `ban_members` permissions.
- [`Permissions.text()`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L168) no longer contain the `read_messages`/`view_channel` permission.
- Added `Permissions.advanced()` which is an alias for `Permission.administrator`.

This commit also modifies the [`Permissions.all_channel()`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L147) class method, by adding the `stream` and `priority_speaker` permissions which were missing.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TheOneMusic** [comment]
Also, I was wondering why there is no `Permissions.all_guild()` factory method, it could be useful.

**Comment by Zomatree** [comment]
no versionadded, plus this is a breaking change so should be set for v2.0.

**Comment by TheOneMusic** [comment]
Thank you. Just wanted to know, why is this a breaking change? It doesn't remove any methods or parameters, nor does it change method/parameters names (it simply modifies the return value).

**Comment by bijij** [comment]
It's been debated as to whether it is or not.
On one hand, it's changing a value which was pretty much treated as a constant.
On the other hand the value is tied to the discord UI and as such would make sense to match what the UI displays.

**Comment by Rapptz** [comment]
I don't have a strong lean towards this being a breaking change or not.

As was mentioned above, the documentation does not explicitly mention what the constant value is and ties it to the UI. It makes sense to change it if the UI changes however some people might be relying on the old value. It's a tricky subject.

**Comment by TheOneMusic** [comment]
I guess it makes sense to update. I mean discord is updating and we can't stay with the old UI design forever. The advantage of this one is also to split up general, membership and advanced permissions into separate categories for more control, and also update `Permissions.all_channel()` which were missing recent permissions.

**Comment by TheOneMusic** [comment]
So, will this be part of update 1.6 or 2.0? What do you think is best?

**Comment by bijij** [comment]
Personally I'd say it's non breaking and should be in 1.7

But others probably disagree.

**Pull request closed without merging**
