### PR TITLE
Added State and Details

### PR DESCRIPTION
**Pull request by colcrunch**
Adds the state and details information to the game object for rich presences.

https://discordapp.com/developers/docs/topics/gateway#activity-object

### CODE REVIEW

**Comment by NCPlayz** [comment]
Bots aren't allowed to have Rich Presence, and selfbots aren't allowed either.

**Comment by Modelmat** [comment]
Nope, this adds getting info from the game of a user (someone who has a rich presence) as well.

**Comment by Gorialis** [comment]
It has been [said before](https://github.com/Rapptz/discord.py/pull/908#issuecomment-345438446) that this will be implemented in a different way, using slotted separate type-sensitive classes. This is better because activities actually contain [a lot more properties](https://discordapp.com/developers/docs/topics/gateway#activity-object) than what this PR offers, and having the dynamics and empty attributes thrown onto Game will waste memory and increase confusion.
Additionally, the PR's implementation is likely to make users think they can submit such rich presence activites when they actually cannot.

**Comment by colcrunch** [comment]
If implementation is planned. Might as well close this PR then.

**Pull request closed without merging**
