### PR TITLE
Fixed Spelling Error

### PR DESCRIPTION
**Pull request by Sanjay-B**
"Familiarise" should be "familiarize"

### CODE REVIEW

**Comment by Helehelehele** [comment]
It's not an error. It's the British spelling.

**Comment by Sanjay-B** [comment]
https://www.google.com/search?q=familiarize&rlz=1C1GGRV_enUS760US760&oq=familiarize&aqs=chrome..69i57j0l5.3689j0j7&sourceid=chrome&ie=UTF-8

No, the correct way is "familiarize" not "familiarise".

**Comment by NCPlayz** [comment]
https://typos.are-la.me/61bb24.png

**Comment by Rapptz** [comment]
At the very least I hope you learned something new.

Feel free to consult [the wiki](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences) for more differences between spelling.

**Pull request closed without merging**
