### PR TITLE
Support 3.11

### PR DESCRIPTION
**Pull request by tuna2134**
## Summary

Add 3.11 ~~and 3.12~~ to setup.py

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by No767** [comment]
Is 3.12 supported on master? I know 3.11 is, but unsure if 3.12 is supported or not

**Comment by tuna2134** [comment]
> Is 3.12 supported on master? I know 3.11 is, but unsure if 3.12 is supported or not

3.12 will release almost, so I added

**Comment by No767** [comment]
> > Is 3.12 supported on master? I know 3.11 is, but unsure if 3.12 is supported or not
> 
> 3.12 will release almost, so I added 

None of the workflows use 3.12 right now nor have I tested 3.12 on the master branch. Unless you can prove that 3.12 indeed works with no issues and everything works as intended, I would highly suggest not marking 3.12 support since it would be misleading

**Comment by tuna2134** [comment]
If 3.12 will released, we can merge this
I am not recommend to merge this.

**Comment by No767** [comment]
Fair enough

**Comment by tuna2134** [comment]
Well, tomorrow, 3.12 is going to release.

**Comment by No767** [comment]
Note that aiohttp doesn't build on 3.12, so we have to wait until aiohttp gets support for 3.12 before testing it

**Comment by tuna2134** [comment]
I see

**Comment by tuna2134** [comment]
I removed 3.12

**Pull request merged**
