### PR TITLE
Add Permissions.priority_speaker

### PR DESCRIPTION
**Pull request by slice**
"Users with this permission have the ability to be more easily heard when talking. When activated,
the volume of others without this permission will be automatically lowered."

8th bit.

### CODE REVIEW

**Comment by Werseter** [comment]
Does such permission even exist in Discord's endpoint? Even if so, I'm curious as of, if at all, was it introduced.

**Comment by jwshields** [comment]
@Werseter I just updated to the newest Canary build and I see it in my options.

**Comment by Werseter** [comment]
Interesting addition it is then, I am checking the regular documentation of Discord now and still have not found a proper entry, but then I suppose I should be looking at a beta one.

**Comment by Werseter** [comment]
Well, even though this correctly seems to implement the flag, as I've tested it about now, still things in Canary may change and may confuse potential users if introduced to the library before an official release of the feature. While not invalid, this should most probbably be suspended and introduced, with proper changes if needed, as this feature may get expanded somehow, later on.

**Comment by Harmon758** [comment]
Relevant documentation:
https://github.com/discordapp/discord-api-docs/pull/638
https://github.com/discordapp/discord-api-docs/commit/5adf4cb1c68b86573b82b9dc8d473d7da0176c00

**Pull request merged**
