### PR TITLE
updates avatar warning docs to show that animated pfps now work.

### PR DESCRIPTION
**Pull request by JDJGInc**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by JDJGInc** [comment]
I am not sure about the warning but I think the docs updating may be important.

**Comment by Rapptz** [comment]
You can just remove the line and move it down to the avatar parameter docs.

**Comment by JDJGInc** [comment]
Alright.

**Comment by Rapptz** [comment]
That's fine but it should be `are` instead of `is` (the original had the same grammar mistake)

**Comment by JDJGInc** [comment]
Would you look to make the order like:

``Only image formats supported for uploading are JPEG, GIF, PNG, and WEBP.``

or keep the order as is?

and then make it

``Only image formats supported for uploading are JPEG, PNG, GIF, and WEBP.``

**Comment by Rapptz** [comment]
The order doesn't matter

**Comment by JDJGInc** [comment]
image
alright here's it now then:

**Pull request merged**
