### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by Demizon3433**
Added hyphens to two words in the first sentence

## Summary

This PR doesn't fix any significant issues, just adds hyphens to two compound words, that they were missing.

## Checklist

- [ ] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [X] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by RGBCube** [comment]
such a quality pull request

**Comment by cobaltgit** [comment]
"Update README.rst"

**Comment by nerdguyahmad** [comment]
@RGBCube @cobaltgit Stop making rude and useless comments on PRs

**Comment by Rapptz** [comment]
Thanks for the PR but I don't think these need to be hyphenated.

**Pull request closed without merging**
