### PR TITLE
Add support for get voice state

### PR DESCRIPTION
**Pull request by Puncher1**
## Summary

This PR adds the functionality to get the voice state over the http endpoints.

Related PR: 
- https://github.com/discord/discord-api-docs/pull/7061

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by chredeur** [comment]
It would be nice to merge this functionality 😅

**Review by Rapptz — CHANGES_REQUESTED** [review]
It's not clear from the documentation what would happen if the member does not have a voice state. I'm assuming it returns a 404, but I'm not at liberty to test.

**Comment by Puncher1** [comment]
> It's not clear from the documentation what would happen if the member does not have a voice state. I'm assuming it returns a 404, but I'm not at liberty to test.


Yes it does

image

**Comment by Rapptz** [comment]
Should probably add that to the `Raises` section then.

**Review by Rapptz — APPROVED** [review]

**Pull request merged**
