### PR TITLE
style: add typing metadatas

### PR DESCRIPTION
**Pull request by SaidBySolo**
### Before

image

### After
image

I am using pylance strict option.

After applying that change, it will no longer complain about not being able to find the stub file.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Please note that `discord.ext.commands.bot` is not a publicly exported namespace.

**Comment by SaidBySolo** [comment]
A problem also occurs in the following cases:
image

Do I have to use it in the following way unconditionally?
```py
from discord.ext import commands

bot = commands.Bot("")
bot.run()
```
I prefer the absolute import.

**Comment by Rapptz** [comment]
> Do I have to use it in the following way unconditionally?

Yes, this is the only supported export.

Ideally, `from discord.ext.commands import Bot` would work too but the `discord.ext.commands.bot` module is technically private.

**Comment by SaidBySolo** [comment]
``from discord.ext.commands import Bot``
I want the following format, but if py.typed is applied, as mentioned above, unintended problems may occur, so I will close this PR.

**Pull request closed without merging**
