### PR TITLE
clean up parenthesized await expressions

### PR DESCRIPTION
**Pull request by bmintz**
Removes superfluous parens surrounding await expressions.

### CODE REVIEW

**Comment by BluePhoenixGame** [comment]
There is a reason for the parentece. If you know the priority rule in math then you would know that you have parentece as the number one priority. And it's kinda the same for python. The parentece are there since it's await that the function will get ran first before it gets returned, not risking any bug/error.

**Comment by DavidArchibald** [comment]
No, they are not needed. Using the same math analogy you used: return is the lowest priority. The only case it would be needed is something such as `return (await my_coroutine())["prop"]` but that isn't a good usage either: it's doing too much on one line.
This entire PR likely boils down to a style opinion.

**Comment by BluePhoenixGame** [comment]
Ah, yes. That is true. Well then I do approve of this.

**Comment by Hornwitser** [comment]
If you look a bit into the history of that code you'll find it's left overs from when yield from was used (which did require parenthesis).

**Pull request closed without merging**
