### PR TITLE
Remove namedtuples

### PR DESCRIPTION
**Pull request by Taarek**
## Summary

It removes the usage of namedtuples to avoid a future ``deny_new`` issue.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

I was not able to test integrations because I don't have access to said guild, but the other stuff works fine.

### CODE REVIEW

**Comment by SebbyLaw** [comment]
Could something like this be used to cut down on repetition?
```py
class FakeNamedTuple:
    def __init__(self, **kwargs):
        for k in self.__slots__:
            setattr(self, k, kwargs.get(k))

    def _asdict(self):
        return {k: getattr(self, k) for k in self.__slots__}

    def __repr__(self):
        return '%s(%s)' % (self.__class__.__name__, ', '.join('%s=%r' % (k, getattr(self, k)) for k in self.__slots__))
```
ex:
```py
class BanEntry(FakeNamedTuple):
    __slots__ = ('reason', 'user')
```

**Review by iomintz — CHANGES_REQUESTED** [review]
This kills the repr.

**Comment by jack1142** [comment]
This breaks tuple unpacking (among other things) and BanEntry is specifically documented as a namedtuple. Maybe change for d.py v2.0?

**Comment by mikeshardmind** [comment]
Tuple unpacking is *already* version unsafe if discord ever adds anything to what they include in a ban entry and this needs to be updated for that.

**Review by Rapptz — CHANGES_REQUESTED** [review]
A few nits.

1) This can't be removed from `BanEntry` since it's explicitly documented to be a namedtuple there and it doesn't have any of the issues that made `_Overwrites` annoying.
2) This is missing `__repr__` for those classes.
3) If `_asdict` is not used then don't bother defining it.

**Review by Rapptz — APPROVED** [review]

**Pull request merged**
