### PR TITLE
Makes bot.process_commands ignore commands from bots

### PR DESCRIPTION
**Pull request by Modelmat**
This follows recommended usage of discord bots, and removes the need to override
on_message for just this. If they don't want it to ignore the bot, just override it.

### CODE REVIEW

**Comment by LyricLy** [comment]
I don't see a need for this. It's also misleading.

**Comment by Modelmat** [comment]
Alternatively, we could add this to `bot.process_commands(message)`. This would completely remove this issue? (Although it would be a breaking change to those who have split it into sections to edit).
This could be controlled by the kwarg in the bot.

**Comment by fourjr** [comment]
This should be a parameter in the `commands.Bot` init `ignore_bots` similar to `case_insensitive`, default to false

**Comment by Rapptz** [comment]
I did this one myself since there were a lot of conflicts.

**Pull request closed without merging**
