### PR TITLE
Add support for splash(_url) to invites

### PR DESCRIPTION
**Pull request by DismissedGuy**
I noticed that you apparently couldn't get the splash from a server invite if you're not in it yourself

### CODE REVIEW

**Comment by ApfelTV** [comment]
will this thing here see activity soon?

**Comment by ApfelTV** [comment]
> 2 lines of code
>> `The code is messy`
>>> makes sense

**Comment by DismissedGuy** [comment]
My additions are set using the exact same way as `guild.name` is, so if this is apparently the wrong way to do it I don't see why guild.name is there.

**Comment by ApfelTV** [comment]
What about an answer? I like the activity here.

**Comment by Harmon758** [comment]
> Add support for splash(_url) to invites
> Undocumented change
> 
> 2 lines of code
> The code is messy
> 
> makes sense

It's undocumented as in this PR doesn't add these changes to the documentation, and code doesn't need to be numerous in lines to be untidy.

> My additions are set using the exact same way as guild.name is, so if this is apparently the wrong way to do it I don't see why guild.name is there.

`guild.name` isn't undocumented or set dynamically. Nor does it have any semblance to this PR's `guild.splash_url`.

**Comment by ApfelTV** [comment]
dude are you kidding me

**Comment by ApfelTV** [comment]
just accept this shit
2 friggn lines dude

**Comment by DismissedGuy** [comment]
even though this might not be the correct way to do this, how else would you go about adding this feature? it's not a full guild object, so would it be worth to make a separate object just for this?

**Comment by ApfelTV** [comment]
Hey if this code is bad and you say we could do this on another way, what about showing the code for the other way?

**Comment by LittleEndu** [comment]
Showing how something is done completely misses the point of what PRs are used for. If something is not critical to the system no owner/collaborator/contributor is going to PR a fix for it. If you want to have something fixed, you are the one who needs to make code that actually works.

**Comment by DismissedGuy** [comment]
Could you guys at least give me some suggestions on how else to achieve this? I feel like it isn't worth making a separate object for (didn't get any response on that comment, so just gonna assume it isn't). The 2nd line could be cleared up I guess, but I personally don't see another way.

**Comment by DismissedGuy** [comment]
I've cleaned it up a bit, does it look okay?

**Pull request closed without merging**
