### PR TITLE
Added Persistence script

### PR DESCRIPTION
**Pull request by Hyperclaw79**
**__Persistence__** is a small script that constantly monitors network status and auto restarts bot when a network drops and returns back (say, due to a powercut). Don't have to manually restart a timed out bot anymore. Made for _Windows._ Can work for other platforms also with small alterations.

__Modified Requirements.txt__:
`Psutil` is required by the Persistence script. 

Please review and lemme know what you think of it.

### CODE REVIEW

**Comment by Rapptz** [comment]
No.

The rewrite version of the library already has a reconnect logic.

**Comment by Hyperclaw79** [comment]
Hence posted it under Async hoping that a branch will be made for Rewrite. But either way, I guess I'm way too late. 😅

**Comment by Rapptz** [comment]
I'm not gonna add reconnect logic requiring psutil and tracking into the main lib. Not like that.

If people want reconnect logic then they can upgrade.

**Comment by Hyperclaw79** [comment]
Oh i see. Alrighty then. I guess I'll upgrade too, sooner or later.
And I'll see if I can work on any other tiny scripts meanwhile. Hope you don't mind a PR or two. :)

**Pull request closed without merging**
