### PR TITLE
Change docstrings to raw-strings

### PR DESCRIPTION
**Pull request by BeatButton**
Second try at #1566. I deleted the branch for that one though so I just figured I'd do a new PR.

### CODE REVIEW

**Comment by Hornwitser** [comment]
You forgot three docstrings with backslashes.  One in calls.py (line 135) and two in client.py (line 66, 291).  Furthermore the `\N{name}` escapes in client.py line 709-719 looks like they should be escaped as well.

**Comment by BeatButton** [comment]
Thanks! For some reason they didn't show up as ```DeprecationWarning```s, which is what I was using to test them. As for ```\N{name}``` eacapes, those are valid Python escapes and don't need to be turned into raw strings as far as I can figure.

**Comment by Hornwitser** [comment]
It's a code example.  When not escaped they turn into the emoji in the built docs, which makes me wonder if that was unintentional, as the emoji chars might as well have been used directly when the docs shows them as the emoji.

**Comment by BeatButton** [comment]
Oh, I see. I wouldn't know whether that's intentional or not.

**Comment by bmintz** [comment]
Leaving them unescaped would preserve their current appearance in the docs. Adding the r prefix for those docstrings would require changing the emojis to their actual Unicode form.

**Comment by BeatButton** [comment]
Unless, of course, the intent is to show the escapes as raw text to demonstrate how it can be done.

**Pull request closed without merging**
