### PR TITLE
Typing fixes

### PR DESCRIPTION
**Pull request by bryanforbes**
## Summary

* Make some Cog methods positional-only
* Fix maybe_coroutine and MaybeCoroFunc
* Mark stub functions that can be coroutines as returning MaybeCoro

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
> Mark stub functions that can be coroutines as returning MaybeCoro

I don't think I agree with this change. Is there a reason it was done?

**Comment by Rapptz** [comment]
The set of users who use strict is incredibly small and generally aren't the type of people I'm trying to please in the library. The incompatible method error for example will always trigger when a generic is passed as bound even though it's technically okay.

A big issue I have with this is usability. A lot of tooling helpfully autocomplete methods when overriding and this one will give users a bizarre signature to override that includes a private alias type.

**Comment by bryanforbes** [comment]
> A big issue I have with this is usability. A lot of tooling helpfully autocomplete methods when overriding and this one will give users a bizarre signature to override that includes a private alias type.

This is a really good concern to have. Let me know what you'd like me to do with this PR. I can split it into two: one for fixing `maybe_coroutine()` and one for the positional-only params.

**Comment by Rapptz** [comment]
I think just the maybe_coroutine fixes are okay. The positional-only parameter change seems like an unnecessary breaking change in this case.

**Comment by bryanforbes** [comment]
This has stagnated and the `maybe_coroutine()` changes have been handled in 06c257760bdedd39c37a7eb12f0338ac60b48c20. Closing this.

**Pull request closed without merging**
