### PR TITLE
Add missing payload types to http.py

### PR DESCRIPTION
**Pull request by bijij**
## Summary

Adds a few missing payload types to http.py

- edit template
- edit widget
- create / edit stage instance
- upsert global commands

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
I don't think I want to use typed dicts for payload types

**Comment by bijij** [comment]
A fair few already do, so figured at that point all should. 🤷

**Comment by Rapptz** [comment]
The ones that use it also function as models, they're not exclusive to the edit payload.

**Comment by Rapptz** [comment]
Discussed in the Discord.

**Pull request closed without merging**
