### PR TITLE
Added colors

### PR DESCRIPTION
**Pull request by Middledot**
## Summary

Add 2 colors to colours.py because I thought it might be useful

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by itzsimpleboii8282** [comment]
What are these colors? Are they somehow related to those colors in discord or in standard colour section.

**Comment by Middledot** [comment]
> What are these colors? Are they somehow related to those colors in discord or in standard colour section.

They're both discord colors, one to match the embed color, and the other for light mode as there's one for dark mode

**Comment by JelNiSlaw** [comment]
discord.py only has colors from Discord's color picker and branding. You can easily use your own colors if you need them.

**Comment by Middledot** [comment]
> discord.py only has colors from Discord's color picker and branding. You can easily use your own colors if you need them.

These are colors from discord's themes.
There's the white mode color and the color of the embed

**Comment by JelNiSlaw** [comment]
A better name would be just `white` instead of `light_theme`. What's the use case of an embed color? Because "invisible embed borders" are not an official feature, and if you really want them you can make use the color value yourself.

**Comment by Middledot** [comment]
> A better name would be just `white` instead of `light_theme`. What's the use case of an embed color? Because "invisible embed borders" are not an official feature, and if you really want them you can make the color value yourself.

The embed color could be an alternative to putting the hex value for a full one color embed.

**Comment by ahts97** [comment]
You checked the checkbox stating that you have updated the documentation to reflect the changes - you did not do that. Please pay attention to what are you doing. We can now doubt your code has been tested if you did not even read what have you checked.

Either way, there is absolute no reason to set the theme colours as presets, some of the arguments being:
- These colours are not transparent - some people use the light theme, some use the dark theme - this change is simply misleading;
- They are not official branding colours, meaning it's not supported by Discord and is a subject to change without prior announcements;
- The colours might vary on different platforms - small colour shifts make an unpleasant visual experience.

You said it's often used - myself, being on Discord from around 2017, I have never seen a single bot use it. You aren't everyone.

You can store these colours for yourself in an easily accessible place, but not in the actual library code.

**Comment by Middledot** [comment]
> There is absolute no reason to set the theme colours as presets, some of the arguments being:
> 
> * These colours are not transparent / embed matching - some people use the light theme, some use the dark theme - this change is simply misleading;
> * They are not official branding colours, meaning it's not supported by Discord and is a subject to change without prior announcements;
> * The colours might vary on different platforms - small colour shifts make an unpleasant visual experience.
> 
> You said it's often used - myself, being on Discord for around 4 years, I have never seen a single bot use it. You aren't everyone.
> 
> You can store these colours for yourself in an easily accessible place, but not in the actual library code.

Since the docs are autogenerated, I assumed the changing the documentation meant adding or editing the noted under the function, so my bad.

Even if users have different modes, there is already a dark theme color, so I thought there should be the opposite themed colors?

**Pull request closed without merging**
