### PR TITLE
Update readme installation-guide to python3.8

### PR DESCRIPTION
**Pull request by nerrixDE**
## Summary

(README.md install-instruction): Encourage python3.8 (stable) usage, python3.6 is quite old.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by AtieP** [comment]
Old doesn't mean it doesn't work.

**Comment by AtieP** [comment]
I recommend you to add: `Recommended Python 3.8`.

**Comment by nerrixDE** [comment]
> Old doesn't mean it doesn't work.
sure, but it's clear that the instructions are just a recommendation tho

**Comment by Rapptz** [comment]
It's not a recommendation. It's an example. That's what "e.g." means.

**Pull request closed without merging**
