### PR TITLE
New example

### PR DESCRIPTION
**Pull request by FrostiiWeeb**
## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by mesub7 — CHANGES_REQUESTED** [review]
I wouldn't say this is _really_ advanced and there a quite a few things that need to be changed. 

• Sections of code need to be appropriately commented.
• Single quotes should be used where possible. 
• Have you thought about file persistence?

**Comment by ppotatoo** [comment]
There isn't much use case for an economy without persistent storage.

**Review by itzsimpleboii8282 — COMMENTED** [review]
I do not understand the intention of creating it, we already have an example like this which shows about creating a basic bot. The code is also missing comments to explain what a specific thing does.

**Comment by Rapptz** [comment]
Sorry this example is too low quality.

**Comment by FrostiiWeeb** [comment]
Yes, now I realize that it's too "low quality" because of these reasons:
Not using an actual database
it isn't too advanced, it's just a simple cog with economy that anybody can do.

**Pull request closed without merging**
