### PR TITLE
Disc and Holy stats; Holy artifact progression

### PR DESCRIPTION
**Pull request by Izzirez**
[dictEntries.txt](https://github.com/Rapptz/discord.py/files/420703/dictEntries.txt)

### CODE REVIEW

**Comment by GetRektByMe** [comment]
Can I ask why on earth this PR exists

**Comment by Pandentia** [comment]
I have the same question as @GetRektByMe

**Comment by martmists** [comment]
why are you replacing d.py with your own project

**Comment by SunDwarf** [comment]
I think this was a failed tracking PR to his own repo that ended up here instead.

**Comment by Rapptz** [comment]
Why

**Comment by Hornwitser** [comment]
Hey @Igkern, (and @Izzirez as well).  I want you to know that forking a Discord library on GitHub is not the way to develop a Discord bot.  You give yourself a tone of trouble with things like keeping up to date with the development with the library for no benefits at all.

Please do like every other sane developer do and make your own repository with your bot code in it, and use pip to install and keep discord.py up to date on your system.

**Comment by TickerOfTime** [comment]
Please, squash your commits too. Learn how commands.ext works and learn how cmd.exe works

**Comment by sr229** [comment]
why do you even contribute

;eyes:

**Comment by neko** [comment]
+1

**Pull request closed without merging**
