### PR TITLE
Update intro.rst

### PR DESCRIPTION
**Pull request by jen140**
### Summary
As futher in the documentation we require to use python3 venv we should have the installation for it done(python3-venv).

### Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [X] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
[`venv`](https://docs.python.org/3/library/venv.html) is a standard Python module. I am unsure what this is installing.

**Comment by jen140** [comment]
For some reason it doesn't work on clean python3 installation on debian 10 as seen in the following picture:
error

**Comment by Werseter** [comment]
Acutally, it is true some distros require installing python3-venv package for Virtual Environments to work8 cze 2020 01:14 Danny <notifications@github.com> napisał(a):
venv is a standard Python module. I am unsure what this is installing.

**Comment by Rapptz** [comment]
Based on that error it seems to me that you don't have pip either.

**Comment by jen140** [comment]
You were correct with that, but after installing it the issue is the same:
error2

**Pull request closed without merging**
