### PR TITLE
[tasks] Added basic support for datetime.time

### PR DESCRIPTION
**Pull request by MrHedmad**
## Summary
This pull adds very basic support for the `datetime.time` objects in the Tasks extension. It's a very simple change, which just shifts the time of execution to align to the 'at' parameter (if any is specified) and then resumes normal loop behavior. 

Do note that from internal testing the loop seems to shift by about 2 seconds when the task is initiated, and the reason is unknown. However, this seems irrelevant to me for everyday usage.

This tries to amend issue #2159 

## Checklist

- [X] If code changes were made then they have been tested.
    - [X] I have updated the documentation to reflect the changes.
- [X] This PR fixes an issue.
- [X] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by feelingnothing** [comment]
Great work, would be cool to see this approved

**Comment by xernphoton** [comment]
OMG i needed this

**Comment by Technerder** [comment]
Looks great!

**Comment by xernphoton** [comment]
i want this

**Comment by Rapptz** [comment]
Hello, thanks for the PR and sorry for the late review.

I am not overly a fan of this implementation for a few reasons.

1. It is more complicated than it should be. The loop class already has all the tools necessary to support this by configuring `_get_next_sleep_time` as the hook function to change if an explicit time is passed.
2. The time delta utility function seems to be using local time despite the times being passed using UTC time. The original implementation tried to be timezone aware, and this seems to toss all of that away.
3. The original specification called for a `times=[...]` parameter that allowed you to pass multiple times if needed, which was a superset of allowing a single time. The specification also referred to this as explicit time, rather than relative time. This means that the loop will only be called at the specified times given. This PR however adds a single parameter named `at` that supports a single time point to start the initial loop .
4. The original implementation blocked both relative times and explicit times, this PR does not due to it being fundamentally different.

**Comment by MrHedmad** [comment]
Thanks for the review Danny.

**Pull request closed without merging**
