### PR TITLE
Add autorestart decorator

### PR DESCRIPTION
**Pull request by AileenLumina**
This adds a decorator that makes the decorated coroutine restart when interrupted by a connection issue.

### CODE REVIEW

**Comment by AileenLumina** [comment]
I need a few opinions on this:

- What should the decorator be called? The current name isn't great. `restart_after_disconnect`?
- Should the parameter `pause` be optional?
- Should the decorator also accept regular functions?

**Comment by AileenLumina** [comment]
#959 can be closed.

**Comment by AileenLumina** [comment]
Fixed all the things that were suggested to be fixed on the discord.py Discord server, this should now hopefully be okay to merge.

**Comment by Rapptz** [comment]
Superseded by the `tasks` extension package.

**Pull request closed without merging**
