### PR TITLE
Adding Reaction.remove()

### PR DESCRIPTION
**Pull request by CapnS**
This addresses #610 about adding a .remove() to Reactions. This will make it cleaner and easier to remove reactions from their messages. I have tested this and it works as intended. As always, suggestions and criticisms are always welcome!

### CODE REVIEW

**Comment by Nekorooni** [comment]
I think it's better to use .format() instead of % style formatting.

**Comment by CapnS** [comment]
> I think it's better to use .format() instead of % style formatting.
> 
> `'{0.name}:{0.id}'.format(emoji)`

I copied that static method straight from [message.py](https://github.com/Rapptz/discord.py/blob/rewrite/discord/message.py#L724-L736) where it does the same thing.

**Comment by laggycomputer** [comment]
If we want to establish a clear library standard (examples use `.format`, some lib code uses `%s`, that's another issue. `%s` is fine for now.)
.

**Comment by Vexs** [comment]
I'm reasonably certain this won't work. 

Your addition of `user_id` ties the reaction object to a specific user- which, in this case, I suspect is just going to be the first person who added the reaction originally. (Or, if removed, the second person, etc. Whatever discord dispatches.) Reaction objects as it stands are not tied to users- instead just having a count, and a method to get reaction users. This is why [message.remove_reaction](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Message.remove_reaction) takes an abc.Snowflake.
In light of that, you need to consider the NotFound exception in your documentation as well. 

This also fails to cover conditions where you are removing your own reaction. 

Additionally, I find the example fairly pointless. It's a rather self-explanatory method.

**Comment by CapnS** [comment]
It has been brought to my attention that this will not work. I only tested it with myself and did not realize that this will not work if there are more than one of the same reaction on the message.

**Pull request closed without merging**
