### PR TITLE
Change superclass to subclass in some documentation

### PR DESCRIPTION
**Pull request by kaeptmblaubaer1000**
### Summary

It makes no sense that methods accept "Command or superclass objects", because this for example includes a plain `object()`.

### Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Lgtm.

**Comment by kaeptmblaubaer1000** [comment]
I changed the source of the translations, thus I needed to change the translations too... wdym with "ruin the diffing"?

**Comment by Rapptz** [comment]
These are built by a program occasionally. The program does a comparison and then applies it.

**Comment by kaeptmblaubaer1000** [comment]
This should fully continue to work AFAIK.

**Pull request merged**
