### PR TITLE
Added __eq__ to Message class in message.py

### PR DESCRIPTION
**Pull request by TurretAA12**
### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by TurretAA12** [comment]
I am not sure how I would go about updating the documentation.  Please let me know!

**Comment by BeatButton** [comment]
Duplicate of #772, unfortunately

**Comment by TurretAA12** [comment]
O I did not see that, my bad. Would you like me to close?

**Comment by Vexs** [comment]
I think it's worth re-approaching again because after literally three years of every single mention of this coming up, PR being made, or expectation of users, every single instance I can recall has had the exact same id=id class=class comparison. Not just because it falls inline with every other object in the library both logically and philosophically, but also because it's the bloody expected behavior.

**Comment by Rapptz** [comment]
> I am not sure how I would go about updating the documentation. Please let me know!

There's a supported operations table, you can just copy it from everywhere else.

**Comment by TurretAA12** [comment]
Ya I think that the current implementation (which is just the default `object.__eq__`) is not the most intuitive functionality.  If you are also concerned about comparing content why not also add a `compare_content()` method. Maybe something along the lines of...
```python
def compare_content(self, other):
    return isinstance(other, self.__class__) and self.id == other.id and self.content == other.content
```

**Comment by TurretAA12** [comment]
So what's the status of this PR? Should I close it or is this change up for debate?

**Comment by TurnrDev** [comment]
> Ya I think that the current implementation (which is just the default `object.__eq__`) is not the most intuitive functionality. If you are also concerned about comparing content why not also add a `compare_content()` method. Maybe something along the lines of...
> 
> ```python
> def compare_content(self, other):
>     return isinstance(other, self.__class__) and self.id == other.id and self.content == other.content
> ```

Doesn't Python treat `==` and `is` differently? Maybe we can make use of that.

**Comment by muddyfish** [comment]
It's not treated differently in a way that would help this particular problem

**Comment by TurnrDev** [comment]
Ah ok

**Pull request merged**
