### PR TITLE
Fixes everything.

### PR DESCRIPTION
**Pull request by CapnS**
### Summary

Fixes all remaining issues in rewrite.

### Checklist

- [X] If code changes were made then they have been tested.
    - [X] I have updated the documentation to reflect the changes.
- [X] This PR fixes an issue.
- [X] This PR adds something new (e.g. new method or parameters).
- [X] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by NCPlayz** [comment]
Just checked everything, seems good!

**Comment by laggycomputer** [comment]
10/10. April Fools!

**Comment by APRILFOOL2019** [comment]
APRILFOOL

**Comment by HAHA01042019** [comment]
HAHA! LMAO NICE JOKE... Can u not spam repo with unnecessary junk?? I'm fed up with email spam...

**Comment by HAHA01042019** [comment]
can u like frick off.

**Comment by diceroll123** [comment]
The changes page killed chrome on my phone, thanks I hate it.

**Pull request closed without merging**
