### PR TITLE
register guild_only commands as guild commands

### PR DESCRIPTION
**Pull request by odrling**
## Summary

This PR allows guild_only commands to share the name of a global command.
It was an issue when migrating to discord.py v2 from a personal fork as we were using that for one of the commands of our bot.
We've been running that for about a month without any issues, but I'm not sure if this would be the expected behaviour for this parameter.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Thanks but this isn't the point of the `guild_only` decorator and I'm not really sure I agree with the storage changes this would enable. It should also be noted that on top of being a decorator this is also a boolean parameter. 

Can I ask what the use case for this is? If you wanted to have a global command with the same name as a guild command you could just attach it to a guild ID and work from there.

**Comment by odrling** [comment]
Well the point was to avoid hard-coding guild IDs in the code.
The guild command complements the global command (they have different subcommands) with the only exception of not being available in DM with the bot.

**Comment by Rapptz** [comment]
You can use a named constant instead.

The point of `guild_only` is to implement the `dm_permission` toggle. Anything more than that is way outside the scope of the feature. Especially guild commands that aren't actually bound to any specific guild but all guilds. 

Thanks for the PR, sorry it could not be accepted at this time.

**Comment by odrling** [comment]
Hmm actually, would it be fine to use just set the guilds parameter of the
command to a special value without changing the semantics of guild_only ?
With my current changes I suppose we could define a command like 
```python
@command()
@guilds(None)
async def my_command(...):
  ...
```
But ideally it would be a special value instead of `None`.

**Comment by Rapptz** [comment]
The IDs aren't validated in any form so you can use whatever sentinel you want.

**Pull request closed without merging**
