### PR TITLE
Change to simpler pip install command

### PR DESCRIPTION
**Pull request by froggal**
## Summary
`python3 -m pip install -U discord.py` to `pip3 install discord.py`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by froggal** [comment]
+ Ja README

**Comment by froggal** [comment]
Not related to this PR, but changing OS X to macOS in ja

**Comment by ImVaskel** [comment]
generally speaking, it's preferred to be verbose with pip, as it could point to a different installation than intended.

**Comment by sarthhh** [comment]
there are many cases where `pip3` isn't directly accessible through the path, while `python3 -m pip` always works. so whats the point of this?

**Comment by pikaninja** [comment]
this also kinda just... doesnt work. If you remove the quotes around `discord.py[voice]` it breaks on macos

**Comment by Rapptz** [comment]
Thanks for the PR. Usage of `-m pip` is actually recommended since it gives you the appropriate pip for the interpreter being used.

**Pull request closed without merging**
