### PR TITLE
Add per-guild member avatar support

### PR DESCRIPTION
**Pull request by JustAnyones**
## Summary

This pull request addresses the #7054 by adding support for per-guild member avatars. To put simply, this PR adds a ``Member.guild_avatar`` property to get member guild avatar. If the guild-specific avatar is unavailable, it just calls ``Member.avatar``.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
This feature is unstable (i.e. not documented to work according to Discord and can break at any time).

That being said, this has a few bikeshedding considerations that were bypassed in this PR which is also why it wasn't immediately implemented. We have a few choices here:

First, `Member.avatar` can return the guild avatar and fallback to the user avatar if not given. This also means making `Member.user` a public read-only attribute so you can access `Member.user.avatar` for the original avatar. Alternatively, `Member.user_avatar` as an attribute.

Second, this PR's implementation which is `Member.guild_avatar` while keeping `Member.avatar` the same.

Third, a `Member.display_avatar` which does the same thing `nick` does in this library. Basically returning guild avatar if available, otherwise fall back to user avatar. This property would have to be part of `User` as well. So.. `Member.avatar` is the user's avatar, `Member.guild_avatar` is *only* the guild avatar, and `Member.display_avatar` would do `guild_avatar` or fallback avatar.

There were too many choices and we didn't know which one to go with.

**Comment by JustAnyones** [comment]
You bring up a good point. Personally, I feel like the third option would be the right choice as it would be symmetrical with the display name.

Moreover, in that implementation, you could tell whether the member has a guild avatar at all.

However, that's just my humble opinion and I would like if others could express their thoughts on it.

**Comment by Rapptz** [comment]
I think the `display_name` proposal is the most popular given an informal vote if you want to go ahead with it.

**Comment by JustAnyones** [comment]
I've observed the discord.py server, seing the third option be the popular one, I implemented the changes.

**Review by Rapptz — CHANGES_REQUESTED** [review]
Mostly good, but this is missing the same attribute for `BaseUser`.

**Review by Rapptz — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
