### PR TITLE
add typing metadata

### PR DESCRIPTION
**Pull request by ShineyDev**
## Summary

This PR adds the `py.typed` marker file to the lib directory and the manifest. I've also added the PyPI classifier.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
This feels premature.

**Review by bryanforbes — CHANGES_REQUESTED** [review]
Since typing is not finished, the contents of `py.typed` should be `partial\n`.

**Comment by ShineyDev** [comment]
I'm aware. I discussed this PR with Danny back in May, [it'll be merged when typing is complete](https://discord.com/channels/336642139381301249/812600992116899861/846149096607318036).

**Review by Rapptz — APPROVED** [review]
This is now basically complete 🎉

**Pull request merged**
