### PR TITLE
added category support

### PR DESCRIPTION
**Pull request by SirYwell**
I just added category support to this branch because I needed it right now. I saw it already in the rewrite branch but I wasn't sure which one is the default branch for releases. If you don't need i here, just ignore/delete this pull request.

### CODE REVIEW

**Comment by ZeLarpMaster** [comment]
This doesn't allow you to create or edit channels with categories though.

A few changes in http.py are needed to allow that too.

**Comment by laggycomputer** [comment]
Async is no longer developed. Rewrite is the preferred branch for new PRs at the moment.

**Comment by Harmon758** [comment]
This exists as [`GuildChannel.category`](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.abc.GuildChannel.category) on the rewrite branch.

**Comment by SirYwell** [comment]
I'll close this as it is outdated

**Pull request closed without merging**
