### PR TITLE
Bumped copyright years to 2019.

### PR DESCRIPTION
**Pull request by laggycomputer**
See #1828. Please let me know if I missed any copyright notices...

### CODE REVIEW

**Comment by BluePhoenixGame** [comment]
You missed basically every file where there is actual code. Like **discord/embeds.py.** And all other files in the **discord** folder.

**Comment by RDIL** [comment]
@Rapptz

**Comment by RDIL** [comment]
why not

**Comment by RDIL** [comment]
I see

**Comment by laggycomputer** [comment]
Whoa there. Lazy attempt? More like performing janitorial work. If it's rebased, fine. As long as the changes are in there, I don't care how they're applied.

**Comment by CapnS** [comment]
Can we not fight over PRs? If Danny wants to add this he will, it's not up to us to decide.

**Pull request closed without merging**
