### PR TITLE
Fix Attribute Error when the client joins a server that server is ``None`` so then server.get_member causes that AttributeError.

### PR DESCRIPTION
**Pull request by AraHaan**
I caught this when my bot was joining a server. This is a fix I think.

### CODE REVIEW

**Comment by khazhyk** [comment]
I'm not sure that guild_member_update should ever be sent before the first guild_create. Do you have websocket logs of this behavior happening?

**Comment by AraHaan** [comment]
It happens when I join servers on my bot that my bot was not a part of and sadly I could never get the logs from d.py itself to show. FeelsBadMan

**Comment by cookkkie** [comment]
It happens for me too. But just ignoring it is bad.

**Comment by Rapptz** [comment]
Fixed it differently I believe.

**Pull request closed without merging**
