### PR TITLE
(GitHub CI) Bump crowdin_download workflow versions

### PR DESCRIPTION
**Pull request by ArjunSharda**
## Summary

This pull request will bump versions in the crowdin_download workflow file for example for actions/checkout from version 2 to version 3.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by jack1142 — CHANGES_REQUESTED** [review]
github-script@v5 introduced a breaking change that this project is affected by that you did not address in this PR (see the `.github/workflows/scripts/close_and_reopen_pr.js` file):
https://github.com/actions/github-script#breaking-changes-in-v5

**Comment by ArjunSharda** [comment]
> github-script@v5 introduced a breaking change that this project is affected by that you did not address in this PR (see the `.github/workflows/scripts/close_and_reopen_pr.js` file): https://github.com/actions/github-script#breaking-changes-in-v5

Changed the title and description, thanks.

**Comment by jack1142** [comment]
> Changed the title and description, thanks.

This doesn't fix the problem. You have to update the script appropriately based on the documentation I linked so that it still works after the version bump that you made here.

**Comment by Rapptz** [comment]
Thanks but the script is working as-is so this is unnecessary.

**Pull request closed without merging**
