### PR TITLE
Replace .format in basic_voice.py with f-strings.

### PR DESCRIPTION
**Pull request by elfq**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by gogurtenjoyer** [comment]
Currently, the library still supports Python 3.5.3, where f-strings aren't supported.

**Comment by cclauss** [comment]
https://devguide.python.org/#status-of-python-branches

**Comment by XuaTheGrate** [comment]
As of right now, Python 3.5 is still supported with discord.py. This will be changed in the 2.0 release, however until then, the support will remain.

**Comment by cclauss** [comment]
When you are ready, just run `pyupgrade --py36-plus **/*.py` and it will make these changes across the codebase.

**Comment by NightZan999** [comment]
> When you are ready, just run `pyupgrade --py36-plus **/*.py` and it will make these changes across the codebase.

Thanks

**Pull request closed without merging**
