### PR TITLE
Fix image urls

### PR DESCRIPTION
**Pull request by Pysics**
## Summary

Fix image urls

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
This isn't correct. The root directory for the docs build *is* docs.

**Comment by Pysics** [comment]
@Rapptz Without this images aren't displayed. Please re-check it.

**Comment by Rapptz** [comment]
https://discordpy.readthedocs.io/en/stable/discord.html
https://discordpy.readthedocs.io/en/master/discord.html
https://discordpy.readthedocs.io/en/v1.7.3/discord.html

**Comment by Pysics** [comment]
:+1:

**Pull request closed without merging**
