### PR TITLE
Thank Decorator.

### PR DESCRIPTION
**Pull request by Diakarus**

### CODE REVIEW

**Comment by khazhyk** [comment]
i dont believe this is valid syntax

**Comment by Diakarus** [comment]
... but it is

**Comment by khazhyk** [comment]
did you try running it yourself?

**Comment by Diakarus** [comment]
I don't do any of this stuff. I just finished learning HTML and I'm trying to learn JS. I just did this per Decorator's request.

**Comment by khazhyk** [comment]
...maybe let him make the pull request himself

**Comment by Diakarus** [comment]
Danny blocked Decorator.

**Pull request closed without merging**
