### PR TITLE
Add display_name kwarg to bot.add_cog

### PR DESCRIPTION
**Pull request by TheTrain2000**
This kwarg allows for the names of cogs to be changed upon addition of a cog in it's setup function.

This is a suggested resolution to #601

### CODE REVIEW

**Comment by TheTrain2000** [comment]
I didn't add the typehint because I didn't see it used in other places within the cog and stuck with consistency.

That is not necessary. `if display_name` is completely valid to check whether or not `display_name` is `None`.

Anyways, Danny has stated that he intends to implement the naming of cogs in the form of meta classes. I'm leaving this PR open in the case Danny will use it to display information on his implementation of this.

**Comment by MysterialPy** [comment]
Consistency? What if someone passes in an int for example? Or an empty list etc

And I don't see why you would check for None (especially since you didn't type hint).

`x if x` will fail on any Falsy, whereas `x if x is not None` will return True. Why would we want our name to be an empty string? Or an empty dict, set, list etc etc.

For example:
```
thing = ""

if thing:  # Will be False...

if thing is not None:  # Will be True
```

**Comment by TheTrain2000** [comment]
If a user were to pass an empty string, it should be `False`. Cogs should not have empty strings for names.

Also, I've stated that this PR isn't going to be updated in my previous comment.

**Comment by MysterialPy** [comment]
That's my point boi. Look at your code you check `x if x is not None`

**Comment by TheTrain2000** [comment]
Oh. :blobthinkingfast: I'll push a commit in the case anyone uses this in the future, but this won't be the official implementation.

**Comment by MysterialPy** [comment]
Haha 👍 Yeah I remember Danno talking about the meta class thing

**Pull request closed without merging**
