### PR TITLE
Add issues and pull requests templates.

### PR DESCRIPTION
**Pull request by PapyrusThePlant**
## Description
This adds templates to issues and pull requests for people to follow when they create one. They are aimed to be clear and easy to follow, include self explanatory sections and comments for additional details about each section.

## Motivation and Context

This PR was motivated by all the code help issues created in this repo and the poorly explained or invalid bugs reported.

## How Has This Been Tested?

The templates were added on a [temporary test repo](https://github.com/PapyrusThePlant/Foo), upon opening an issue or a pull request, its content is automatically filled with the corresponding template.  Feel free to try it there, this repo will stay alive as long as this PR is open

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have looked through previous open **and** closed pull requests for duplicates of this update/change.
- [x] My code is well written.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MysterialPy** [comment]
This looks nice, though `My code is well written.` seems a little odd to me.

**Comment by jwshields** [comment]
I'm making an assumption, but I would think the "My code is well written" line is more about perceived cleanliness, versus hacky, awkward lines of inefficient code?

RE Issue template: I believe environment information should be on top before expected/current behavior.
It would prompt people to list their information first, for support people, knowing off the bat whether it's async/rewrite, linux/windows, and possibly unique to that situation.
If the template is too long, users could be liable to not fill it out completely, and if system information is near the bottom, including that information might be missed/ignored.

**Comment by SourSpoon** [comment]
asking explicitly for peoples d.py version and python version may also be helpful

**Comment by NCPlayz** [comment]
I don't think the dpy version matters since they would need to pr to that specific branch, unless they manage to mess it up somehow

**Comment by scragly** [comment]
PRs might be branch specific, but I don't think Issues are.

**Comment by NCPlayz** [comment]
Ah yeah, that's a good point.

**Comment by NCPlayz** [comment]
So that's issue-exclusive.

**Comment by jwshields** [comment]
It's _usually_ easy to infer the branch being used from the code in issues, but having it explicitly stated would stop "mixups" like #991

**Comment by PapyrusThePlant** [comment]
Yes the `My code is well written` is to make people reflect on their code quality.

`Library version used` is present in the `Environment details` section of the issue template.  
The optimal placement of that section for the person writing the issue is kinda subjective, so whichever floats most people's boat. For readability it might be better to have it on top indeed, so that's where it now is.

**Comment by retke** [comment]
You can make comments in markdown, so they're not shown in the preview. You have to do it like this:

```Markdown
<!--
This is a comment
-->

<!-- This is also a comment -->
```

You can make the explanations comments, so users won't have to remove them (like "Provide a general summary of the issue in the Title above" or "Put an `x` in all the boxes that apply")

**Comment by PapyrusThePlant** [comment]
The issue was that those comment would show up in the webhook's embed.

**Comment by mrc0mmand** [comment]
@Rapptz would you mind looking into this? It could help with the wave of python 3.7 and user-code issues (assuming that people would read it).

**Comment by TheSnoozer** [comment]
I just stumbled over this (so sorry for the very late comment)....and would fully agree that this is in general a good idea, but sadly barely followed by the users who create issues.

Some personal remarks (feel free to ignore):
- Github supports to create [multiple issue templates](https://help.github.com/articles/about-issue-and-pull-request-templates/) and [multiple pull request templates](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/). The current templates are essentially one template that tries to express different cases (e.g. the section `Your Environment` seems only relevant if you submit a bug). IMHO when I submit a feature request it would feel weird that I could safely ignore half of the template.
- When going through the various things that is being asked by the template (e.g. `Python version` / `Library version`) I immediately would start to ask `how do I get the information that is actually helpful?`. It might be more helpful to provide clear instructions on how to get the information that is relevant (e.g. `Include your python version that can be obtained by running python --version`). This also applies for `My code follows the code style of this project.`...how do I verify that? It seems more helpful to say `I have verified my changes by running pylint` (or whatever is actually needed to verify)
- Potentially also include `Verify that the bug is also present in the latest version that can be installed by....(include the commit hash)`.  Pip sadly does not report the commit of a package that was installed.
- Isn't `My change requires a change to the documentation.` and `I have updated the documentation accordingly.` the same?

**Comment by laggycomputer** [comment]
#1957 😃

**Pull request closed without merging**
