### PR TITLE
Change message.clean_content to handle all @ signs

### PR DESCRIPTION
**Pull request by SexualRhinoceros**
This change should future proof it from all added functionalities such as role mentioning as well with the only downside being reasonably a few added characters to the total limit.

### CODE REVIEW

**Comment by abalabahaha** [comment]
This will block accidental @ everyones tho... not cool

**Comment by Hatsuney** [comment]
good

**Comment by fennekid** [comment]
This will break things like emails and URLs though....

**Comment by imayhaveborkedit** [comment]
`re.sub("@[^@]", "@\u200b", result)`

**Comment by SexualRhinoceros** [comment]
if you want to maintain emails and URLs, you can easily use `message.content`

clean_content is meant to strip any and all mentions. I've seen users abuse this in any way possible while running RH1 and this is a change that simply has to be made if you want to say that it cleans all mentions indefinitely from the bot owners end.

Manage Roles not inheriting all permissions W H E N

**Comment by Rapptz** [comment]
When role mentions come out it will probably not be as obvious as "escaping the @ sign". Should the time come for it, `clean_content` will update for it in a different matter.

**Pull request closed without merging**
