### PR TITLE
commands.clean_content: escape || spoilers ||

### PR DESCRIPTION
**Pull request by bmintz**

### CODE REVIEW

**Comment by khazhyk** [comment]
Won't this break code blocks with || in them

**Comment by shikhir-arora** [comment]
Yeah, you'd probably want something along these lines if you want to check specifically:

`input = 'some test text'`
`match = re.match(r"(\|{2}(.*)\|{2})",  input)` 
`sanitize = re.sub(r"(\|{2}(.*)\|{2})", '"\u200B"', input)`

https://regexr.com/47hme

**Comment by bmintz** [comment]
Unmatched \~, \*, and \` are already escaped. I see no need to start only escaping matched spoilers.

**Comment by Rapptz** [comment]
I wonder if it would be better to escape things only if they're matched.

**Pull request closed without merging**
