### PR TITLE
added a shortcut to `reset_cooldown` and some type hinting

### PR DESCRIPTION
**Pull request by Nirlep5252**
## Summary

Added a shortcut for `Command.reset_cooldown` in `Context` so instead of using `ctx.command.reset_cooldown(ctx)` I can just use `ctx.reset_cooldown()` 👍 
And added some type hinting in the `Context` class so users can get better autocomplete in IDEs 👀 

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by JelNiSlaw** [comment]
I'm not sure what's the advantage of this shortcut. You can subclass `Context` and add this method yourself without modifying the library.

**Comment by JDJGInc** [comment]
I would actually use this method, @JelNiSlaw.

**Comment by scrazzz** [comment]
`ctx.reset_cooldown` sounds vague in my opinion.

**Comment by Rapptz** [comment]
I'm not really a fan of this shortcut. Sorry.

**Pull request closed without merging**
