### PR TITLE
fix target id being None raising an error

### PR DESCRIPTION
**Pull request by iyad-f**
## Summary

This PR fixes the error raised when target_id is None and AudiitLogEntry.target is used and a converter is used to return the target

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)
image

### CODE REVIEW

**Comment by iyad-f** [comment]
i see that some converters here can have target_id None so this if target_id is None check would be needed in those converters where target_id must be an int

**Comment by iyad-f** [comment]
i think i messages up with pushing stuff

**Comment by Rapptz** [comment]
This isn't the proper fix for this. The proper fix would be to fix the specific target instead.

**Comment by iyad-f** [comment]
i added another commit doing that should i make another pr?

**Pull request closed without merging**
