### PR TITLE
Added property link

### PR DESCRIPTION
**Pull request by BluePhoenixGame**
Added a new function which has the property decorator, it returns the link to the message you can get through right clicking a message a selecting "copy link" with developer mode on.

### CODE REVIEW

**Comment by Phxntxm** [comment]
https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Message.jump_url

**Comment by NCPlayz** [comment]
This is redundant as there is already [Message.jump_link](https://github.com/Rapptz/discord.py/blob/e46d862b512f2297ed0dc7146b6a50e5a1ea058c/discord/message.py#L462).

**Comment by ItWasAllIntended** [comment]
This has already been implemented on rewrite [here](https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Message.jump_url) and is not a developer mode only features

**Comment by BluePhoenixGame** [comment]
Ooh, i did not see that `Message.jump_link`. And i wasn't able to do the "copy link" action without developer mode on. Sorry for wasting your time guys. I am closing this PR then.

**Pull request closed without merging**
