### PR TITLE
Typo code blocks

### PR DESCRIPTION
**Pull request by Puncher1**
## Summary

Typo fixes for code blocks. 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Looking at the commit count on this, it's probably a good idea for future contributions to use a separate branch instead. If you're using the GitHub editor this is done by using this option when you edit the file:

image

**Comment by Puncher1** [comment]
@Rapptz I'm using GitHub Desktop, how would I do it there?

**Comment by Rapptz** [comment]
I don't use GitHub desktop. On regular git CLI you would switch branches by doing `git switch -c my-cool-change` in the repository. This [article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches#switching-between-branches) seems to show a UI to switch and create branches as well.

> There are still the other commits when I create a new branch

Yes, your old commits will still remain. I don't know how to fix this in GitHub Desktop, only the CLI. Sorry.

**Comment by Puncher1** [comment]
@Rapptz Was able to fix it by changing the fork behavior, thanks though!

**Pull request merged**
