### PR TITLE
Added return type hint for some functions

### PR DESCRIPTION
**Pull request by Harshal6927**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by searchify7 — APPROVED** [review]
Somehow........

**Comment by Heurican** [comment]
> Smh

?

**Comment by SebbyLaw** [comment]
"Magic" or "dunder" methods like `__init__` and `__eq__` do not require annotations and are not processed by type checkers.

Almost all of these changes are unecessary or wrong. Please don't open pull requests with the intention of "farming" contributions.

**Comment by Heurican** [comment]
farming? what does that mean?

**Comment by Harshal6927** [comment]
> "Magic" or "dunder" methods like `__init__` and `__eq__` do not require annotations and are not processed by type checkers.
> 
> Almost all of these changes are unecessary or wrong. Please don't open pull requests with the intention of "farming" contributions.

I am just getting used to codebase I have not contributed much in open source you can look in my profile. So while I was checking different files I found some of them didn't had return type so I though it I'll add it my intention is not for farming.

**Comment by SebbyLaw** [comment]
> > "Magic" or "dunder" methods like `__init__` and `__eq__` do not require annotations and are not processed by type checkers.
> 
> > 
> 
> > Almost all of these changes are unecessary or wrong. Please don't open pull requests with the intention of "farming" contributions.
> 
> 
> 
> I am just getting used to codebase I have not contributed much in open source you can look in my profile. So while I was checking different files I found some of them didn't had return type so I though it I'll add it my intention is not for farming.

Apologies for being so hostile. Your intentions were fine, keep contributing to open source!

**Comment by Rapptz** [comment]
Hello,

This PR is fine. It's just formatted incorrectly. This repository uses CI (Continuous Integration) to ensure that all library files are formatted properly. It uses a program called [black](https://github.com/psf/black) to accomplish this. You can download it by doing `pip install -U black`.

The settings for black are located in the root directory of the project where the `pyproject.toml` is located. Make sure to run `black discord/ examples/` in the directory where the `pyproject.toml` is located and it should all fix the formatting issues.

**Review by Rapptz — APPROVED** [review]
Thanks.

**Pull request merged**
