### PR TITLE
add utils.unicode_emoji

### PR DESCRIPTION
**Pull request by sevenc-nanashi**
## Summary

I added `utils.discord_emoji`.
It converts discord's emoji name into unicode emoji.
```python
>>> discord.utils.unicode_emoji("snake")
'🐍'
>>> discord.utils.unicode_emoji("thinking")
'🤔'
>>> discord.utils.unicode_emoji("thinking_face")
'🤔'
>>> discord.utils.unicode_emoji(":cloud:")
'☁️'
```

### Note
[emoji](https://github.com/carpedm20/emoji/) cannot convert discord's emoji name.
```python
>>> emoji.emojize(":thinking:")
':thinking:'
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Heya. Sorry but I don't really want to maintain this list within the library especially since it changes whenever there's a new unicode version and discord updates their libraries.

**Comment by wasi-master** [comment]
btw I just use a vscode extension to achieve the same thing at the moment

**Comment by builderpepc** [comment]
There's also the `discord-emoji` package [here](https://github.com/sevenc-nanashi/discord-emoji) with the same functionality proposed here.

**Comment by Vexs** [comment]
This mapping (and the library you've linked to) are poor implementations of discord's emojis- variation selectors, alternative names, skin-tones, and a couple of special names and names discord doesn't use are miss-mapped- there's about 500 of these improper mappings/missing keys.

That's why I maintain [this mapping](https://gist.githubusercontent.com/Vexs/629488c4bb4126ad2a9909309ed6bd71/raw/da8c23f4a42f3ad7cf829398b89bda5347907fef/emoji_map.json) which has none of these problems.

**Pull request closed without merging**
