### PR TITLE
Add proxy variable

### PR DESCRIPTION
**Pull request by jhqwqmc**
## Summary

Add the use of the proxy variable to the from_url function of the webhook class.

During use, I found that the from_url function did not provide a proxy parameter to pass in. My area requires a proxy to access discord, so I added this parameter.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by No767** [comment]
If you were to ask me, this isn't needed. I would wonder *why* even support proxies for webhooks?

**Comment by Rapptz** [comment]
The reason for this is because you can set the proxies on the `ClientSession` you create instead.

**Comment by jhqwqmc** [comment]
`ClientSession` does not provide proxy variables. You need to pass proxy variables to Webhook.

**Comment by jhqwqmc** [comment]
Needing a proxy is also a helpless move. Our country has blocked the website discord.com.

**Comment by Rapptz** [comment]
Actually it seems you're right, I forgot this change happened to aiohttp a while back. This PR is insufficient though. It needs to support `proxy_auth` parameter as well *and* be properly documented.

**Comment by jhqwqmc** [comment]
I just added `proxy_auth`

**Comment by Rapptz** [comment]
This is still missing documentation, and most likely needs to run black.

**Comment by JDJGInc** [comment]
Oh wow

**Pull request closed without merging**
