### PR TITLE
Use json_or_text helper for parsing webhook responses

### PR DESCRIPTION
**Pull request by nerdguyahmad**
## Summary

This pull request adds proper handling of KeyError caused by Cloudflare by using `json_or_text` helper similar to `HTTPClient`.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
Are there any situations you've seen where this is triggered? The cloudflare bug is pretty old and I was under the impression it was fixed. There was a report about it from a user but they were using a proxy server that seemed to discard the header which invalidated the report.

**Comment by nerdguyahmad** [comment]
> Are there any situations you've seen where this is triggered? The cloudflare bug is pretty old and I was under the impression it was fixed. There was a report about it from a user but they were using a proxy server that seemed to discard the header which invalidated the report.

There was a recent [report in #bikeshedding channel](https://discord.com/channels/336642139381301249/603069307286454290/980034271492333618)

**Comment by Rapptz** [comment]
Yes, that's the user who reported it due to a proxy server given prior history.

**Comment by nerdguyahmad** [comment]
Right, that's fine then.

**Comment by Rapptz** [comment]
I'm not necessarily against it, I'm just wondering. Plus, this change needs to be mirrored in `sync.py` too.

**Comment by nerdguyahmad** [comment]
Alright, I've done it in `sync.py` too. :ok_hand:

**Pull request merged**
