### PR TITLE
Add more detailed description to accent_colour

### PR DESCRIPTION
**Pull request by rperson1508**
## Summary

Added a short description to explain what an accent colour is

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by Rapptz — COMMENTED** [review]
I guess while we're here you should probably mention that it's only given if the user explicitly sets a colour.

**Comment by rperson1508** [comment]
> I guess while we're here you should probably mention that it's only given if the user explicitly sets a colour.

I may be wrong but doesn't Discord automatically take the colour from their avatar?

**Comment by Rapptz** [comment]
Yes but that's done client side, the API does not return that colour. It does this when the `accent_color` is `null`.

**Comment by rperson1508** [comment]
Alright am sorry for replying this late, adding that in now.

**Pull request merged**
