### PR TITLE
make examples on_ready consistent

### PR DESCRIPTION
**Pull request by pikaninja**
## Summary

A couple of the examples had on_ready print in a different format from others. This pr fixes this

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
The single print call version is probably better.

**Comment by pikaninja** [comment]
should i make all of them the single print then?

**Comment by Rapptz** [comment]
Something like 

```py
@bot.event
async def on_ready():
    print(f'Logged in as {bot.user} (ID: {bot.user.id})')
    print('------')
```

**Comment by pikaninja** [comment]
got it

**Review by Rapptz — APPROVED** [review]

**Pull request merged**
