### PR TITLE
get_channel accepts strings not integers

### PR DESCRIPTION
**Pull request by toomuchio**
Misleading confused me for a tad, minor fix.

### CODE REVIEW

**Comment by Rapptz** [comment]
It is a coincidence at best.

**Comment by Rapptz** [comment]
This is wrong. Rewrite uses `int` not `str`

**Comment by toomuchio** [comment]
How long ago did this change I just tried this for the first time today and it wasn't working with ints.

**Comment by Rapptz** [comment]
There are two major versions of the library in the wild at the moment.

- One is rewrite (aka v1.0.0) which uses `int` as IDs.
- The other is v0.16.x which uses `str`.

This PR is for the rewrite branch so it's incorrect.

**Pull request closed without merging**
