### PR TITLE
Add `utils.convert_timestamp`

### PR DESCRIPTION
**Pull request by ChesterWOV-DPY**
#### New Feature
Add `utils.convert_timestamp(timestamp, tz=...)`.
Converts a discord timestamp (for example `<:9999999>`) to a datetime object using `datetime.fromtimestamp`. `tz` is the timezone to convert to.

Not sure if I should also make a Transformer/Converter.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
I'm not really convinced this function is necessary?

**Comment by ChesterWOV-DPY** [comment]
I thought it might be useful if a bot needs to edit a timestamp, I mean, yeah you could hard code the new timestamp inside but well why don't you use `convert_timestamp(msg.content) + timedelta(days=1)`

**Comment by Gorialis** [comment]
I think if this was implemented at all, it would be as a regexing cached slot property on Message similar to `Message.raw_mentions`, but I don't know if the demand is really there. There'd also be a question of how to name it in a non-confusing way (`Message.timestamps` sounds like it would end up being *very* confusing)

**Comment by Rapptz** [comment]
I've denied this before (#7312) so not sure I'll accept this one.

**Pull request closed without merging**
