### PR TITLE
Change wording of InvalidArgument removal in docs

### PR DESCRIPTION
**Pull request by quackbarc**
## Summary

This fixes the grammar of the `versionchanged` note in the docstrings and Japanese localization about replacing InvalidArgument with TypeError or ValueError .

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Rapptz** [comment]
I think instead of that wording something like:

```
This function will now raise <exc> instead of ``InvalidArgument``.
``` is more readily understandable.

**Comment by quackbarc** [comment]
That sounds good too. I'll also get the localization thing reverted, thought the text over there had to be changed as well.

**Comment by quackbarc** [comment]
Actually, for the wording how about
```
This function will now raise <exc> instead of the now-removed ``InvalidArgument``.
```
Could the footnotes still be transparent about what `InvalidArgument` was upfront, or would that still hinder understandability?

**Comment by Rapptz** [comment]
I just think it sounds awkward. Its removal is already mentioned in the migrating guide.

**Comment by quackbarc** [comment]
Gotcha.

**Review by Rapptz — APPROVED** [review]
Thanks.

**Pull request merged**
