### PR TITLE
Allow Lists and Tuples for checking roles

### PR DESCRIPTION
**Pull request by hugopilot**
# Summary

Lists and tuples can now be used to check for roles. 

### Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Vexs** [comment]
What exactly is the usecase for supporting nested lists? Further, this can be greatly improved by use of itertools, but I fail to see why.

**Comment by hugopilot** [comment]
> What exactly is the usecase for supporting nested lists? 

Not having to add a role to every single line when using `@commands.has_any_role` but instead just referencing to a list and update roles there. It's a timesaver, really.

**Comment by zomatree** [comment]
are you unable to do something like this? 
```py
@commands.has_any_role(*your_list)
```

**Comment by hugopilot** [comment]
Ok apperantly that does work.

**Pull request closed without merging**
