### PR TITLE
fixed an issue with 'Overwrites' got an unexpected keyword argument 'deny_new'/'allow_new' 

### PR DESCRIPTION
**Pull request by Xinverse**
### Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Gobot1234** [comment]
This has already been fixed, update to 1.3.4

**Comment by helish88** [comment]
read [this](https://github.com/Rapptz/discord.py/issues/5109)

**Comment by Xinverse** [comment]
It's the same fix as the one you've referenced, but for the deprecated async branch, as some people probably still run some older bots with this older version.

**Comment by skairunner** [comment]
Why was this closed? Even if .16 is deprecated, there is still legacy code out there that runs .16, plus this is a trivial change. I don't see any reason why it shouldn't be merged for a .16.13 release. Yes, .16 is ancient history, but until some large change comes there's not much cost to supporting it still.

**Comment by Phxntxm** [comment]
You said so yourself. Because 0.16 is deprecated. People have had **three years** to update, there's been plenty of time, this is an unsupported version of the library.

**Comment by Rapptz** [comment]
I'm not willing to spend my free time and support on a version that's 3 years old because some people can't let go of it.

**Comment by skairunner** [comment]
Totally fair. I suppose I'll just have to maintain my own legacy package/fork. `discordpy-legacy` it is.

**Pull request closed without merging**
