### PR TITLE
style(__init__): more strict type hint in releaselevel

### PR DESCRIPTION
**Pull request by SaidBySolo**
## Summary

In the releaselevel argument of VersionInfo added Literal type hint.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by SaidBySolo** [comment]
Literal support only in 3.7

**Comment by LostLuma** [comment]
The version currently being worked on in the `master` branch requires Python 3.8 or newer, you don't need to close this PR.

**Comment by SaidBySolo** [comment]
> 현재 `master`분기 에서 작업 중인 버전 은 Python 3.8 이상이 필요하므로 이 PR을 닫을 필요가 없습니다.

Oh thx :D

**Comment by SaidBySolo** [comment]
> The version currently being worked on in the `master` branch requires Python 3.8 or newer, you don't need to close this PR.

I was thinking of backward compatibility, but 3.8 or later is good news. Thank you!

**Pull request merged**
