### PR TITLE
Update copyright year to 2018.

### PR DESCRIPTION
**Pull request by georgeshachem**

### CODE REVIEW

**Comment by JennyDiscord** [comment]
Yeah, I don't see why people are not up with this. It is not still 2017, it is 2018, god.

**Comment by AustinLeath** [comment]
I was going to make a pull request for this very thing.

**Comment by Harmon758** [comment]
This PR is now stale.

**Comment by laggycomputer** [comment]
I definitely didn't just create a PR with the exact same idea.

**Pull request closed without merging**
