### PR TITLE
Deleted

### PR DESCRIPTION
**Pull request by TheOneMusic**
Deleted

### CODE REVIEW

**Comment by apple502j** [comment]
Are you deprecating or deleting?

**Comment by TheOneMusic** [comment]
@apple502j I don't know what is best. Right now is it deprecating in the sense that you can still pass it as arguments but nothing will happen (as it is not making sense now) for backwards compatibility.

**Comment by apple502j** [comment]
1.7 is already out, you can make as many breaking changes as you want

**Comment by TheOneMusic** [comment]
@apple502j Done, thank you!

**Comment by apple502j** [comment]
There are many other places that refer to this feature - can you fix them (e.g. template) as well?

**Comment by TheOneMusic** [comment]
@apple502j I did that. Did I miss others?

**Comment by Taarek** [comment]
Discord has not officially deprecated this last time I checked. You can also still edit and see guild regions. It's just tucked away in the UI

**Comment by TheOneMusic** [comment]
@Taarek I think they did, or they are in the process of so.

**Pull request closed without merging**
