### PR TITLE
Add support for css-style shorthand colours

### PR DESCRIPTION
**Pull request by alvesvaren**
## Summary

Adds support for css shorthand colour codes like `#abc` (which would be expanded to `#aabbcc`) to the colour converter in the commands extension.
## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by avayert** [comment]
This breaks the existing conversion of the `discord.Colour` classmethod `red`

**Comment by apple502j** [comment]
I think it should be good if the if is inside try. Not tested yet though

**Comment by alvesvaren** [comment]
> This breaks the existing conversion of the `discord.Colour` classmethod `red`

Oh, didn't think of that, will fix

**Comment by alvesvaren** [comment]
Now it only works if you have a `#` in the colour code too

**Comment by oliver-ni** [comment]
There's a lot of different ways to do it, but maybe something like this is more consistent with previous behavior..

```py
async def convert(self, ctx, argument):

    # ...

    try:
        if len(arg) <= 3:
            value = int(''.join(i * 2 for i in arg), base=16)
        else:
            value = int(arg, base=16)
        # ...

    # ...
```

**Comment by Rapptz** [comment]
I don't think I really like this behaviour, sorry.

**Pull request closed without merging**
