### PR TITLE
Implement voice receive (Fix #1063)

### PR DESCRIPTION
**Pull request by Crypti-x**
This makes #1063 mergeable

### CODE REVIEW

**Comment by Rapptz** [comment]
This is the PR author's responsibility, not yours.

**Comment by bqv** [comment]
Seriously?

**Comment by bqv** [comment]
Thank you @Bottersnike and @Crypti-x for the effort put into this PR. Shame it's been shot down for pedantry.

**Comment by Rapptz** [comment]
Yes, seriously.

Doing a merge commit is not worthy of a PR. He's not the author of the work so he doesn't get to open this PR. It's not like Bottersnike is incapable of doing the merge on his own computer. It's not "pedantry". It's just proper etiquette.

**Pull request closed without merging**
