### PR TITLE
feat: filename and description kwargs for to_file

### PR DESCRIPTION
**Pull request by DenverCoder1**
## Summary

Adds kwargs to `Asset.to_file` and `Attachment.to_file` for overriding the `filename` or `description` when creating the `File`.

Fixes to docstrings

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by Rapptz — COMMENTED** [review]
I'm not sure I get the point of this considering you can just set the filename and description afterwards, plus these are conversion routines that are meant to transform something from type A to type B with the same information.

The actual changeset looks okay to me, I'm just not sure of the merit of the feature being proposed and I'm not sure it's popular enough to warrant inclusion, especially when there's already a viable and readable alternative.

**Comment by DenverCoder1** [comment]
Yeah, you can set it afterwards and that's what I said originally when it was suggested by kal on the Discord server.

I do think it makes a simpler to be able to do it with 1 line though.

```py
await ctx.send(file=ctx.author.display_avatar.with_format("png").to_file(filename="avatar.png"))
```
vs.
```py
file = ctx.author.display_avatar.with_format("png").to_file()
file.filename = "avatar.png"
await ctx.send(file=file)
```

If you disagree, I could disallow overriding parameters that it is able to get from the Asset or Attachment.

**Comment by Rapptz** [comment]
I generally don't like adding things just to encourage things being done in 1-line since I think that can be more unreadable than not. For example, your example is nearing high density for my taste. That aside, I gave it some thought and I guess there's no real harm in adding it.

**Review by Rapptz — APPROVED** [review]
Thanks.

**Pull request merged**
