### PR TITLE
Added roles parameter to Guild.create_custom_emoji

### PR DESCRIPTION
**Pull request by NCPlayz**
This concludes #1201.

### CODE REVIEW

**Comment by BlackSynder** [comment]
Might as well add it to Emoji.edit() as per https://discordapp.com/developers/docs/resources/emoji#modify-guild-emoji

**Comment by NCPlayz** [comment]
Added `Emoji.edit()`, thanks @BlackSynder.

**Comment by bmintz** [comment]
Needs documentation.

**Comment by Rapptz** [comment]
Another PR is doing this slightly better, #1436

**Pull request closed without merging**
